# Construcción de un espacio semántico

> Ideas clave:

* Cómo representar una palabra en un espacio, donde la distancia hacía otra palabra tenga un sentido semántico o contextual, por ejemplo, la frecuencia y distancia entre palabras
* Cómo reducir el espacio semántico a vectores de máxima información con pocas dimensiones

TEXTO -> TOKENS -> INDEXARLOS -> EMBEDDING (MATRIZ DE CORRELACIÓN / TRANSFORMERS)

## Paso 1. Extraer tokens del texto

In [3]:
archivo = open("../conjuntos/quijote.txt", "r") # Cursor / Objeto al archivo

quijote = archivo.read() # Lee todo el archivo y 
                         # lo carga a memoria como un string <str> (Texto)

archivo.close() # Cerrar el archivo

In [4]:
len(quijote) # Tamaño del string - len(<str>)

1299863

In [5]:
# Autoclausura (cierra solo el archivo)
with open("../conjuntos/quijote.txt", "r") as archivo:
    quijote = archivo.read() # <str>

quijote[:100] # 100 - Caracteres | type(quitoje) <str>

'Miguel de Cervantes Saavedra\nEl ingenioso hidalgo don Quijote de la Mancha\n\nAl Duque de Béjar MARQUÉ'

> Normalización del texto

Manzana <-> manzana

<CA>manzana <-> manzana

Público <-> público

<CA>pu<AC>blico <-> pu<AC>blico

público <-> publicó

pu<AC>blico <-> publico<AC>

publico<AE> <-> publico<AA>

"Hola, ¿Cómo están todos este año?"

[h, o, l, a, <PC>, <PS>, <IA>, <CA>, c, o, <AG>, <PS>, ]

Algunas tokenizaciones:

- Por palabras y espacios (simple)
- Por letras y puntuaciones (fina)
- Por palabras y puntuaciones (estructural)
- N-Gramas de letras (3-grama combina 3 letras o puntuaciones)

Ejemplos:

* [hol, a<sp>m, und, o<em><em>] - 3-grama
* [h, o, l, a, <sp>, m, u, n, d, o, <em>, <em>] - letras y puntuaciones (fina)
* [hola, <sp>mun, do<em><em>] -  4-grama
* [hola, <sp>, mundo] - palabras y espacios
* [don, <PS>, ramon<AA>] - palabras y puntuaciones (estructural)
* [don, <PS>, ramo<AC>n] - palabras y puntuaciones (no estructural)

In [6]:
import unicodedata

marcas = {
    32: "<PS>",
    44: "<PC>",
    191: "<IA>",
    63: "<IC>",
    769: "<AC>",
    771: "<TI>",
}

# ord(caracter) -> entero ASCII (0-255)
def tokenizar(texto):
    vector = []

    texto_normalizado = unicodedata.normalize("NFD", texto)

    for caracter in texto_normalizado:
        # Determinar si es una letra mayúscula A-Z
        if ord(caracter) >= ord("A") and ord(caracter) <= ord("Z"):
            vector.append("<MA>")
            vector.append(caracter.lower())
            continue
        # Determinar si es una letra minúscula a-z
        if ord(caracter) >= ord("a") and ord(caracter) <= ord("z"):
            vector.append(caracter.lower())
            continue
        # Determinar si es una marca de puntuación <PS>, <PC>, <IA>, <IC>, <AC>
        if ord(caracter) in marcas:
            marca = marcas[ord(caracter)]
            vector.append(marca)
            continue
        print(caracter, ord(caracter))
        vector.append("<ND>")

    # vector_a = [ord(caracter) for caracter in texto]
    # texto_normalizado = unicodedata.normalize("NFD", texto)
    # vector_b = [ord(caracter) for caracter in texto_normalizado]
    # vector_c = [chr(ord(caracter)) for caracter in texto_normalizado]
    # print(vector_a)
    # print(vector_b)
    # print(vector_c)
    return vector

tokenizar("Hola, ¿Cómo están todos este año?")

['<MA>',
 'h',
 'o',
 'l',
 'a',
 '<PC>',
 '<PS>',
 '<IA>',
 '<MA>',
 'c',
 'o',
 '<AC>',
 'm',
 'o',
 '<PS>',
 'e',
 's',
 't',
 'a',
 '<AC>',
 'n',
 '<PS>',
 't',
 'o',
 'd',
 'o',
 's',
 '<PS>',
 'e',
 's',
 't',
 'e',
 '<PS>',
 'a',
 'n',
 '<TI>',
 'o',
 '<IC>']

In [7]:
# ó -> [o, ´] -> [111, 769] -> o+Ux301
hex(769) # U

'0x301'

In [8]:
marcas = {
    32: "<PS>",
    44: "<PC>",
    191: "<IA>",
    63: "<IC>",
    769: "<AC>",
    771: "<TI>",
}

def tokenizar(texto):
    matriz = []

    texto_normalizado = unicodedata.normalize("NFD", texto)

    for palabra in texto_normalizado.split(" "): # Corte por espacios forma palabras
        vector = []
        for caracter in palabra:
            # Determinar si el carecter vacíos o blancos es menor a un espacio 32
            if ord(caracter) <= ord(" "):
                vector.append("<PS>")
                continue
            # Determinar si es una letra mayúscula A-Z
            if ord(caracter) >= ord("A") and ord(caracter) <= ord("Z"):
                vector.append("<MA>")
                vector.append(caracter.lower())
                continue
            # Determinar si es una letra minúscula a-z
            if ord(caracter) >= ord("a") and ord(caracter) <= ord("z"):
                vector.append(caracter.lower())
                continue
            # Determinar si es una marca de puntuación <PS>, <PC>, <IA>, <IC>, <AC>
            if ord(caracter) in marcas:
                marca = marcas[ord(caracter)]
                vector.append(marca)
                continue
            print(caracter, ord(caracter))
            vector.append("<ND>")
        matriz.append(vector)

    return matriz

tokenizar("Hola, ¿Cómo están todos este otoño?")

[['<MA>', 'h', 'o', 'l', 'a', '<PC>'],
 ['<IA>', '<MA>', 'c', 'o', '<AC>', 'm', 'o'],
 ['e', 's', 't', 'a', '<AC>', 'n'],
 ['t', 'o', 'd', 'o', 's'],
 ['e', 's', 't', 'e'],
 ['o', 't', 'o', 'n', '<TI>', 'o', '<IC>']]

In [9]:
import re

marcas = {
    32: "<PS>",
    44: "<PC>",
    191: "<IA>",
    63: "<IC>",
    769: "<AC>",
    771: "<TI>",
}

def tokenizar(texto, puntuaciones=True):
    matriz = []

    texto_normalizado = unicodedata.normalize("NFD", texto)

    texto_normalizado = re.sub(r"\n", " ", texto_normalizado)
    texto_normalizado = re.sub(r"\t", " ", texto_normalizado)
    texto_normalizado = re.sub(r"\s+", " ", texto_normalizado)

    for palabra in texto_normalizado.split(" "): # Corte por espacios forma palabras
        vector_base = []
        vector_marcas = []
        posicion = 0
        for caracter in palabra:
            posicion = posicion + 1
            # Determinar si el carecter vacíos o blancos es menor a un espacio 32
            if ord(caracter) <= ord(" "):
                vector_marcas.append("<PS>")
            # Determinar si es una letra mayúscula A-Z
            elif ord(caracter) >= ord("A") and ord(caracter) <= ord("Z"):
                vector_marcas.append("<MA>")
                vector_marcas.append(f"<{posicion}>")
                vector_base.append(caracter.lower())
            # Determinar si es una letra minúscula a-z
            elif ord(caracter) >= ord("a") and ord(caracter) <= ord("z"):
                vector_base.append(caracter)
            # Determinar si es una marca de puntuación <PS>, <PC>, <IA>, <IC>, <AC>
            elif ord(caracter) in marcas:
                marca = marcas[ord(caracter)]
                vector_marcas.append(marca)
                vector_marcas.append(f"<{posicion}>")
            else:
                print(caracter, ord(caracter), posicion)
                vector_marcas.append("<ND>")
        # matriz.append("".join(vector_base + vector_marcas))
        if len(vector_base) > 0:
            matriz.append("".join(vector_base))
        if len(vector_marcas) > 0:
            if puntuaciones:
                # matriz.extend(vector_marcas)
                matriz.append("".join(vector_marcas))

    return matriz

tokenizar("Hola, ¿Cómo están todos este otoño?", puntuaciones=False)

['hola', 'como', 'estan', 'todos', 'este', 'otono']

In [10]:
quijote_corpus_tokens = tokenizar(quijote, puntuaciones=True)

quijote_corpus_tokens

; 59 7
. 46 9
: 58 7
. 46 11
. 46 10
. 46 9
. 46 9
« 171 1
» 187 1
. 46 6
. 46 8
. 46 8
; 59 12
. 46 10
- 45 1
. 46 7
. 46 5
; 59 14
. 46 8
- 45 1
- 45 11
. 46 6
. 46 6
: 58 5
- 45 1
. 46 8
. 46 7
. 46 9
. 46 8
- 45 1
- 45 1
- 45 7
: 58 5
- 45 1
; 59 7
̈ 776 8
. 46 12
: 58 11
. 46 5
. 46 5
. 46 7
: 58 5
« 171 1
: 58 6
» 187 8
. 46 9
: 58 10
« 171 1
» 187 1
. 46 2
: 58 9
. 46 7
. 46 5
. 46 4
: 58 7
: 58 6
« 171 1
. 46 6
. 46 7
. 46 8
» 187 9
. 46 8
: 58 9
« 171 1
; 59 9
» 187 4
. 46 4
; 59 5
; 59 9
; 59 6
; 59 6
. 46 11
. 46 8
. 46 8
; 59 12
. 46 6
. 46 7
. 46 7
; 59 6
; 59 8
. 46 6
. 46 5
. 46 14
. 46 11
. 46 13
. 46 9
; 59 5
. 46 5
. 46 10
; 59 10
. 46 11
. 46 7
. 46 5
- 45 4
- 45 5
- 45 3
. 46 4
- 45 5
- 45 4
- 45 6
. 46 7
- 45 5
- 45 4
- 45 3
: 58 4
- 45 6
. 46 7
- 45 7
- 45 5
; 59 6
- 45 8
- 45 6
- 45 8
- 45 5
. 46 6
- 45 5
- 45 5
- 45 5
. 46 6
- 45 5
- 45 5
: 58 6
« 171 1
¡ 161 2
- 45 3
- 45 6
- 45 6
! 33 1
» 187 2
. 46 3
- 45 5
- 45 6
. 46 7
- 45 4
- 45 6
- 45 3
- 45 3
- 45 4
: 58 5
« 171 1
- 45 4
» 187 2
. 46 3
- 45 5
- 45 4
- 45 6
- 45 6
; 59 1
- 45 3
- 45 6
. 46 7
- 45 7
- 45 5
- 45 5
. 46 6
- 45 4
- 45 3
. 46 4
; 59 9
; 59 8
. 46 5
; 59 8
. 46 8
; 59 9
. 46 10
. 46 10
¡ 161 1
! 33 8
¡ 161 1
! 33 6
¡ 161 1
! 33 6
¡ 161 1
! 33 8
. 46 7
. 46 7
. 46 5
. 46 12
¡ 161 1
! 33 7
. 46 11
- 45 6
; 59 7
- 45 8
- 45 7
- 45 7
- 45 8
- 45 5
- 45 5
. 46 6
- 45 5
- 45 6
: 58 7
- 45 7
- 45 6
; 59 7
- 45 4
- 45 5
- 45 5
- 45 7
- 45 3
. 46 4
: 58 7
. 46 8
. 46 7
. 46 7
. 46 5
; 59 11
. 46 5
. 46 6
. 46 6
. 46 7
. 46 8
̈ 776 7
. 46 7
. 46 2
. 46 2
. 46 8
. 46 2
. 46 2
. 46 7
. 46 2
. 46 8
. 46 2
. 46 8
. 46 10
. 46 2
. 46 2
. 46 10
. 46 2
. 46 8
. 46 2
. 46 5
. 46 2
. 46 9
. 46 2
. 46 9
. 46 1
. 46 9
. 46 9
. 46 5
. 46 9
. 46 6
. 46 5
« 171 1
» 187 9
« 171 1
» 187 9
« 171 1
» 187 9
. 46 10
: 58 7
. 46 7
- 45 1
- 45 5
; 59 9
; 59 7
: 58 8
« 171 1
» 187 10
. 46 11
: 58 6
« 171 1
. 46 9
. 46 10
. 46 11
» 187 12
. 46 5
. 46 9
; 59 8
. 46 11
- 45 1
̈ 776 5
- 45 10
: 58 10
; 59 6
. 46 5
; 59 7
. 46 7
; 59 11
. 46 6
. 46 9
. 46 7
. 46 7
. 46 9
. 46 11
. 46 5
; 59 11
. 46 8
. 46 8
; 59 5
; 59 7
. 46 7
; 59 7
. 46 7
« 171 1
» 187 5
. 46 10
; 59 9
- 45 6
; 59 9
; 59 9
; 59 10
« 171 1
» 187 11
. 46 6
« 171 1
» 187 8
; 59 9
« 171 1
» 187 9
« 171 1
» 187 9
. 46 6
« 171 1
» 187 9
« 171 1
» 187 6
« 171 1
» 187 7
. 46 6
. 46 5
: 58 4
- 45 1
: 58 8
« 171 1
» 187 8
¡ 161 1
! 33 5
. 46 6
; 59 13
« 171 1
» 187 7
: 58 7
. 46 7
. 46 8
. 46 11
. 46 6
; 59 8
. 46 7
; 59 11
. 46 8
; 59 8
. 46 10
: 58 9
- 45 1
: 58 8
« 171 1
» 187 8
. 46 9
. 46 9
: 58 9
- 45 1
. 46 7
¡ 161 1
! 33 9
. 46 9
: 58 10
- 45 1
¡ 161 2
! 33 9
. 46 10
. 46 7
. 46 9
. 46 8
. 46 6
; 59 8
; 59 7
. 46 11
. 46 11
; 59 8
. 46 7
. 46 9
. 46 10
( 40 1
) 41 7
; 59 7
; 59 6
: 58 5
- 45 1
. 46 11
; 59 10
: 58 9
- 45 1
; 59 8
. 46 9
. 46 9
: 58 5
- 45 1
. 46 11
: 58 11
- 45 1
« 171 1
» 187 7
. 46 4
: 58 11
- 45 1
; 59 6
. 46 6
. 46 11
. 46 6
; 59 6
; 59 4
; 59 7
; 59 7
: 58 8
- 45 1
« 171 2
: 58 5
; 59 5
» 187 7
; 59 5
; 59 7
. 46 9
; 59 8
. 46 5
- 45 1
- 45 1
- 45 8
. 46 5
. 46 10
. 46 6
- 45 1
- 45 1
- 45 8
. 46 5
. 46 8
. 46 7
; 59 6
. 46 9
; 59 5
. 46 7
. 46 7
. 46 12
. 46 10
; 59 5
: 58 12
- 45 1
. 46 7
. 46 7
- 45 1
- 45 1
. 46 10
; 59 6
; 59 9
; 59 8
. 46 6
. 46 6
; 59 8
. 46 8
̈ 776 5
; 59 7
̈ 776 5
; 59 8
- 45 1
- 45 6
; 59 9
. 46 8
; 59 12
; 59 5
. 46 6
. 46 9
; 59 8
. 46 7
. 46 6
; 59 5
: 58 5
- 45 1
¡ 161 2
! 33 7
. 46 13
( 40 1
) 41 6
. 46 4
- 45 1
- 45 9
: 58 5
- 45 1
; 59 7
. 46 7
. 46 7
. 46 8
- 45 1
- 45 8
. 46 7
. 46 8
: 58 5
- 45 1
¡ 161 2
! 33 5
. 46 11
. 46 7
. 46 6
. 46 6
; 59 11
: 58 10
- 45 1
: 58 7
. 46 9
; 59 11
. 46 8
. 46 10
. 46 13
. 46 7
. 46 9
; 59 9
. 46 7
; 59 11
. 46 5
: 58 8
- 45 1
. 46 6
. 46 6
. 46 7
« 171 1
» 187 7
. 46 8
. 46 7
; 59 10
« 171 1
» 187 9
. 46 9
. 46 11
. 46 5
. 46 6
. 46 8
. 46 12
. 46 6
; 59 8
: 58 5
- 45 1
. 46 7
. 46 6
. 46 8
: 58 7
- 45 1
. 46 7
: 58 11
- 45 1
; 59 5
. 46 5
: 58 5
- 45 1
; 59 6
- 45 1
- 45 6
. 46 9
: 58 11
- 45 1
; 59 4
. 46 7
- 45 1
« 171 3
» 187 10
- 45 1
- 45 8
. 46 9
. 46 6
; 59 9
. 46 6
. 46 6
. 46 4
. 46 4
. 46 5
- 45 1
- 45 5
. 46 8
- 45 1
- 45 1
- 45 8
; 59 7
. 46 5
- 45 1
: 58 8
. 46 5
- 45 1
- 45 1
- 45 9
. 46 10
¡ 161 1
! 33 5
. 46 11
- 45 1
- 45 1
- 45 8
: 58 9
; 59 8
. 46 5
- 45 1
- 45 1
- 45 9
. 46 10
- 45 1
- 45 1
- 45 8
; 59 11
. 46 6
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 9
. 46 10
- 45 1
- 45 1
- 45 8
: 58 9
; 59 9
: 58 7
. 46 10
. 46 12
. 46 7
: 58 8
- 45 1
. 46 8
- 45 1
- 45 1
- 45 8
¡ 161 1
! 33 5
- 45 1
- 45 1
- 45 9
. 46 5
. 46 7
. 46 10
. 46 7
: 58 7
- 45 1
. 46 8
: 58 6
- 45 1
¡ 161 2
! 33 7
; 59 7
. 46 8
. 46 6
; 59 11
; 59 6
: 58 5
- 45 1
- 45 1
- 45 8
. 46 11
. 46 7
. 46 9
; 59 7
; 59 8
. 46 10
; 59 8
; 59 10
. 46 7
: 58 5
- 45 1
. 46 6
: 58 9
- 45 1
; 59 7
. 46 8
- 45 1
- 45 1
- 45 8
. 46 6
. 46 10
: 58 6
- 45 1
- 45 1
- 45 5
. 46 6
¡ 161 1
! 33 4
; 59 7
. 46 7
. 46 7
: 58 5
- 45 1
( 40 1
) 41 8
; 59 8
. 46 5
. 46 8
- 45 1
- 45 1
- 45 5
. 46 6
: 58 6
- 45 1
. 46 10
. 46 10
: 58 5
- 45 1
. 46 8
. 46 8
- 45 1
¡ 161 2
- 45 1
- 45 4
! 33 7
. 46 6
¡ 161 1
! 33 7
; 59 8
. 46 7
- 45 1
¡ 161 2
! 33 3
- 45 1
- 45 5
. 46 6
. 46 6
. 46 10
. 46 8
. 46 8
. 46 8
. 46 8
. 46 5
; 59 10
: 58 5
- 45 1
; 59 11
. 46 6
. 46 6
- 45 1
- 45 1
- 45 8
: 58 11
; 59 6
. 46 5
: 58 4
; 59 10
. 46 9
: 58 5
- 45 1
; 59 6
. 46 6
- 45 1
- 45 1
- 45 8
; 59 10
. 46 9
- 45 1
- 45 1
- 45 5
. 46 6
. 46 4
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
- 45 5
. 46 6
. 46 6
. 46 10
- 45 1
- 45 1
. 46 5
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
- 45 1
- 45 5
. 46 8
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 4
. 46 6
. 46 6
- 45 1
- 45 1
. 46 5
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
- 45 5
; 59 10
. 46 10
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 5
. 46 6
. 46 7
. 46 4
- 45 1
- 45 1
; 59 5
. 46 8
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 5
. 46 6
. 46 9
. 46 6
. 46 5
- 45 1
; 59 11
« 171 1
» 187 7
. 46 8
. 46 6
: 58 5
- 45 1
. 46 13
- 45 1
- 45 1
- 45 5
. 46 6
; 59 8
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 5
; 59 6
. 46 11
; 59 13
. 46 7
. 46 6
; 59 12
: 58 5
. 46 7
: 58 9
- 45 1
¡ 161 2
! 33 7
. 46 10
. 46 8
; 59 6
: 58 5
- 45 1
. 46 13
- 45 1
- 45 1
- 45 5
; 59 8
. 46 10
- 45 1
- 45 1
- 45 8
; 59 11
; 59 14
. 46 6
: 58 6
. 46 7
; 59 9
. 46 10
- 45 6
; 59 5
. 46 9
; 59 7
. 46 12
; 59 8
. 46 7
: 58 5
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
; 59 5
: 58 7
. 46 7
« 171 1
» 187 10
. 46 11
- 45 1
« 171 2
» 187 11
- 45 1
. 46 8
- 45 1
- 45 1
- 45 4
« 171 1
» 187 10
« 171 1
» 187 9
. 46 7
- 45 1
- 45 1
- 45 8
; 59 6
. 46 9
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
¡ 161 2
- 45 1
- 45 8
! 33 7
. 46 8
. 46 8
; 59 9
. 46 11
. 46 4
- 45 1
- 45 1
. 46 8
. 46 9
. 46 6
. 46 7
. 46 9
. 46 9
. 46 9
. 46 4
; 59 8
. 46 7
; 59 5
; 59 6
. 46 9
. 46 10
. 46 10
: 58 4
- 45 1
. 46 4
: 58 8
- 45 1
: 58 5
; 59 6
. 46 7
. 46 8
- 45 1
- 45 1
- 45 6
. 46 9
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 6
. 46 11
; 59 6
. 46 6
- 45 1
- 45 1
- 45 8
; 59 9
. 46 11
- 45 1
- 45 1
- 45 7
. 46 7
: 58 9
- 45 1
; 59 7
. 46 7
- 45 1
- 45 1
. 46 6
- 45 1
- 45 1
- 45 4
. 46 7
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
- 45 1
- 45 8
: 58 10
; 59 9
. 46 8
. 46 9
: 58 6
- 45 1
. 46 8
: 58 5
- 45 1
. 46 6
; 59 8
. 46 6
: 58 7
. 46 10
- 45 1
¡ 161 2
! 33 5
- 45 1
- 45 7
. 46 8
- 45 1
- 45 1
- 45 8
; 59 8
: 58 12
; 59 6
. 46 7
- 45 1
- 45 1
. 46 6
. 46 7
; 59 9
; 59 6
: 58 5
- 45 1
« 171 1
» 187 9
« 171 1
» 187 8
. 46 9
; 59 8
. 46 9
- 45 1
- 45 1
- 45 7
. 46 8
; 59 5
. 46 7
- 45 1
- 45 1
- 45 8
. 46 5
- 45 1
- 45 1
- 45 7
; 59 8
. 46 8
. 46 9
; 59 9
. 46 12
. 46 6
. 46 9
. 46 8
. 46 7
. 46 9
. 46 9
. 46 10
. 46 6
. 46 9
. 46 13
. 46 9
; 59 8
. 46 8
. 46 7
; 59 7
. 46 11
. 46 10
. 46 14
: 58 6
. 46 7
; 59 9
. 46 7
: 58 7
; 59 7
. 46 10
. 46 8
. 46 6
. 46 11
: 58 5
- 45 1
: 58 5
« 171 1
» 187 7
. 46 8
« 171 1
» 187 7
. 46 8
: 58 7
. 46 9
; 59 5
. 46 7
. 46 9
. 46 9
. 46 8
. 46 9
« 171 1
» 187 9
« 171 1
» 187 8
. 46 9
« 171 1
» 187 11
. 46 12
« 171 1
» 187 7
« 171 1
» 187 7
« 171 1
» 187 8
. 46 9
. 46 10
; 59 11
. 46 10
: 58 9
. 46 6
; 59 9
. 46 7
: 58 7
: 58 7
. 46 8
; 59 10
; 59 10
. 46 10
¡ 161 1
! 33 7
; 59 7
. 46 7
; 59 9
. 46 7
; 59 8
. 46 9
: 58 9
- 45 1
: 58 10
. 46 9
. 46 8
- 45 1
. 46 9
̈ 776 6
. 46 1
. 46 10
: 58 5
- 45 1
. 46 6
: 58 8
- 45 1
. 46 6
. 46 9
. 46 7
. 46 10
: 58 5
- 45 1
; 59 8
. 46 5
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 7
; 59 8
. 46 10
- 45 1
- 45 1
- 45 8
. 46 10
: 58 5
- 45 1
- 45 1
- 45 7
; 59 9
. 46 6
̈ 776 5
. 46 9
- 45 1
- 45 1
- 45 8
. 46 10
- 45 1
- 45 1
. 46 6
- 45 1
- 45 1
- 45 8
. 46 7
. 46 6
. 46 8
- 45 1
- 45 1
- 45 6
. 46 16
. 46 8
- 45 1
- 45 1
. 46 8
- 45 1
¡ 161 2
! 33 4
- 45 1
- 45 7
- 45 1
- 45 1
- 45 8
; 59 8
. 46 9
̈ 776 5
. 46 10
: 58 5
- 45 1
. 46 5
: 58 5
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
; 59 9
. 46 10
: 58 5
. 46 11
- 45 1
- 45 1
- 45 7
. 46 11
: 58 6
. 46 5
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
; 59 5
- 45 1
- 45 7
. 46 6
- 45 1
. 46 8
. 46 6
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
¡ 161 2
! 33 10
- 45 1
- 45 8
. 46 9
; 59 5
. 46 7
. 46 8
: 58 6
. 46 8
- 45 1
- 45 1
- 45 7
; 59 13
. 46 10
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
- 45 1
- 45 7
. 46 13
. 46 9
. 46 7
; 59 6
. 46 12
. 46 9
; 59 8
. 46 8
. 46 9
. 46 7
: 58 5
- 45 1
; 59 7
: 58 5
. 46 7
- 45 1
¡ 161 2
! 33 7
- 45 1
- 45 7
; 59 8
. 46 10
. 46 8
; 59 9
. 46 6
- 45 1
. 46 8
. 46 8
. 46 6
. 46 9
. 46 11
: 58 8
- 45 1
. 46 5
: 58 8
. 46 6
. 46 10
. 46 8
. 46 6
: 58 10
; 59 6
. 46 9
. 46 9
. 46 13
. 46 8
. 46 10
. 46 8
. 46 9
; 59 6
. 46 7
. 46 13
. 46 9
. 46 8
( 40 1
) 41 8
. 46 11
. 46 11
: 58 5
- 45 1
; 59 6
. 46 7
. 46 7
: 58 5
- 45 1
. 46 8
; 59 11
. 46 5
- 45 1
- 45 1
. 46 5
: 58 7
- 45 1
. 46 9
. 46 9
. 46 6
. 46 8
. 46 9
. 46 8
. 46 8
. 46 8
. 46 7
. 46 6
. 46 10
: 58 5
« 171 1
» 187 6
. 46 7
; 59 9
. 46 5
. 46 9
; 59 6
: 58 8
. 46 5
. 46 10
; 59 6
: 58 4
- 45 1
. 46 9
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
. 46 10
. 46 9
. 46 7
. 46 7
. 46 8
: 58 5
- 45 1
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 5
. 46 1
- 45 1
- 45 1
. 46 4
- 45 1
- 45 1
- 45 8
; 59 9
. 46 8
. 46 9
; 59 11
. 46 6
; 59 1
. 46 6
- 45 1
- 45 1
- 45 9
. 46 6
- 45 1
- 45 1
- 45 4
; 59 6
. 46 4
- 45 1
- 45 1
. 46 6
; 59 8
. 46 7
- 45 1
. 46 5
- 45 1
- 45 1
. 46 8
: 58 9
- 45 1
. 46 6
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 6
. 46 6
: 58 13
« 171 1
; 59 6
; 59 7
; 59 7
» 187 5
. 46 6
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 6
. 46 5
; 59 7
. 46 9
: 58 7
. 46 5
. 46 8
; 59 8
. 46 11
. 46 12
: 58 7
. 46 6
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 6
; 59 7
. 46 5
- 45 1
- 45 1
- 45 8
; 59 5
. 46 5
- 45 1
- 45 1
- 45 8
. 46 10
; 59 5
. 46 6
. 46 6
; 59 7
. 46 5
. 46 5
; 59 14
. 46 6
. 46 11
; 59 10
. 46 7
- 45 1
- 45 1
- 45 8
. 46 7
- 45 1
. 46 5
. 46 11
. 46 6
. 46 9
; 59 8
. 46 7
; 59 7
. 46 1
: 58 7
. 46 6
. 46 8
; 59 7
. 46 12
. 46 7
. 46 7
; 59 5
. 46 9
; 59 8
. 46 6
. 46 10
. 46 12
. 46 6
- 45 1
- 45 1
- 45 8
. 46 7
- 45 1
¡ 161 2
! 33 5
- 45 1
- 45 8
. 46 7
; 59 7
. 46 9
. 46 6
. 46 8
. 46 6
. 46 8
. 46 11
. 46 7
. 46 7
. 46 5
. 46 13
. 46 7
: 58 5
- 45 1
. 46 9
- 45 1
- 45 1
- 45 8
. 46 6
. 46 12
; 59 7
. 46 5
. 46 8
. 46 10
: 58 8
- 45 1
. 46 7
; 59 11
. 46 6
; 59 5
. 46 9
- 45 1
- 45 1
- 45 8
« 171 1
» 187 7
. 46 7
. 46 7
. 46 3
. 46 13
. 46 6
: 58 5
- 45 1
. 46 9
- 45 1
- 45 1
- 45 8
. 46 5
. 46 7
. 46 9
. 46 9
. 46 7
: 58 10
; 59 5
. 46 11
- 45 1
- 45 1
- 45 10
. 46 11
- 45 1
- 45 1
- 45 8
; 59 8
. 46 10
. 46 5
- 45 1
- 45 1
- 45 10
; 59 6
. 46 6
. 46 5
. 46 10
. 46 11
- 45 1
- 45 1
- 45 8
: 58 9
; 59 7
. 46 8
- 45 1
- 45 1
- 45 10
; 59 13
. 46 10
. 46 8
̈ 776 4
. 46 7
. 46 10
̈ 776 4
. 46 9
; 59 9
; 59 9
. 46 6
. 46 6
. 46 6
; 59 9
; 59 7
; 59 9
. 46 7
. 46 8
. 46 9
; 59 7
¡ 161 1
! 33 6
. 46 5
¡ 161 1
! 33 12
¡ 161 1
! 33 6
. 46 6
. 46 5
¡ 161 1
! 33 4
̈ 776 4
. 46 6
. 46 10
. 46 9
. 46 9
. 46 7
: 58 6
; 59 9
. 46 7
. 46 7
; 59 4
; 59 6
̈ 776 4
- 45 1
; 59 8
. 46 8
; 59 6
. 46 7
. 46 8
: 58 6
- 45 1
; 59 7
. 46 11
. 46 7
- 45 1
- 45 1
. 46 8
- 45 1
- 45 5
; 59 5
. 46 10
. 46 6
: 58 5
̈ 776 6
. 46 11
: 58 7
. 46 7
. 46 9
. 46 10
( 40 1
) 41 7
̈ 776 6
̈ 776 6
. 46 11
. 46 6
. 46 7
. 46 6
: 58 7
- 45 1
. 46 6
. 46 10
- 45 1
- 45 1
- 45 7
- 45 1
- 45 1
. 46 8
̈ 776 6
; 59 4
. 46 8
̈ 776 6
. 46 11
: 58 10
. 46 9
̈ 776 6
. 46 8
; 59 6
: 58 5
- 45 1
¡ 161 1
! 33 8
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 6
: 58 5
. 46 8
- 45 1
- 45 1
- 45 8
. 46 9
. 46 6
- 45 1
- 45 1
. 46 6
- 45 1
- 45 1
- 45 8
. 46 6
; 59 3
. 46 8
; 59 10
: 58 7
. 46 6
. 46 10
: 58 9
- 45 1
. 46 6
. 46 1
: 58 11
- 45 1
. 46 7
: 58 8
. 46 10
; 59 8
. 46 15
- 45 1
- 45 1
- 45 7
; 59 5
. 46 10
. 46 11
. 46 3
. 46 5
. 46 9
. 46 7
. 46 10
; 59 10
. 46 9
. 46 5
: 58 7
. 46 9
; 59 6
. 46 7
; 59 10
. 46 7
- 45 1
- 45 1
- 45 7
. 46 9
: 58 5
- 45 1
. 46 6
- 45 1
- 45 1
- 45 8
. 46 5
- 45 1
- 45 1
- 45 6
. 46 6
- 45 1
- 45 1
- 45 9
. 46 7
- 45 1
- 45 1
- 45 6
. 46 8
- 45 1
- 45 1
. 46 11
- 45 1
- 45 1
- 45 6
. 46 6
- 45 1
- 45 1
. 46 5
- 45 1
- 45 1
- 45 6
. 46 7
: 58 10
. 46 9
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 7
; 59 4
. 46 5
. 46 7
. 46 8
. 46 9
. 46 8
: 58 5
- 45 1
; 59 1
. 46 4
; 59 7
: 58 8
. 46 9
; 59 11
; 59 7
. 46 4
. 46 8
. 46 7
. 46 5
. 46 5
; 59 9
. 46 5
¡ 161 1
! 33 5
. 46 11
; 59 10
. 46 7
. 46 7
. 46 9
: 58 9
- 45 1
- 45 1
¡ 161 2
- 45 1
- 45 9
! 33 6
- 45 1
- 45 1
- 45 8
. 46 10
. 46 6
. 46 7
. 46 8
. 46 7
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
- 45 7
. 46 8
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 7
. 46 10
- 45 1
- 45 1
- 45 8
; 59 10
. 46 7
; 59 7
. 46 6
. 46 4
- 45 1
- 45 1
- 45 7
. 46 8
. 46 9
; 59 6
¡ 161 1
! 33 6
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
. 46 5
; 59 7
: 58 4
- 45 1
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
- 45 7
; 59 8
. 46 9
- 45 1
- 45 1
- 45 8
. 46 5
. 46 9
. 46 11
: 58 8
- 45 1
- 45 1
- 45 1
- 45 8
. 46 4
; 59 13
: 58 5
- 45 1
. 46 11
- 45 1
- 45 1
- 45 8
. 46 11
; 59 9
. 46 5
; 59 8
: 58 5
- 45 1
. 46 6
; 59 5
. 46 8
. 46 9
. 46 6
; 59 11
. 46 7
; 59 8
; 59 10
. 46 5
. 46 7
. 46 9
. 46 4
; 59 5
. 46 5
: 58 5
- 45 1
. 46 4
- 45 1
- 45 1
- 45 7
¡ 161 1
! 33 10
. 46 9
. 46 5
. 46 6
. 46 9
. 46 8
: 58 5
- 45 1
; 59 10
. 46 10
- 45 1
; 59 5
; 59 9
: 58 8
. 46 6
. 46 14
. 46 8
. 46 6
- 45 1
¡ 161 2
- 45 1
- 45 8
! 33 12
. 46 10
: 58 5
. 46 7
- 45 1
- 45 1
- 45 7
; 59 4
( 40 1
) 41 8
; 59 6
. 46 5
- 45 1
- 45 1
- 45 8
; 59 14
. 46 8
- 45 1
- 45 1
- 45 7
: 58 9
. 46 7
- 45 1
- 45 1
- 45 8
. 46 8
; 59 10
: 58 5
- 45 1
¡ 161 1
! 33 7
; 59 7
. 46 7
. 46 10
- 45 1
- 45 1
- 45 7
. 46 10
. 46 8
. 46 11
. 46 6
: 58 8
- 45 1
- 45 1
- 45 1
- 45 8
. 46 9
. 46 11
; 59 10
. 46 8
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
. 46 5
- 45 1
¡ 161 2
- 45 1
- 45 7
! 33 8
- 45 1
- 45 1
- 45 8
. 46 10
- 45 1
- 45 1
- 45 7
. 46 6
- 45 1
- 45 1
- 45 8
. 46 9
. 46 5
. 46 7
. 46 11
; 59 6
: 58 6
- 45 1
; 59 6
; 59 9
. 46 9
« 171 1
» 187 6
; 59 8
; 59 8
: 58 5
« 171 1
» 187 7
. 46 8
: 58 9
- 45 1
: 58 9
; 59 6
; 59 7
; 59 7
; 59 11
; 59 8
; 59 9
; 59 8
; 59 8
; 59 6
; 59 8
. 46 8
; 59 6
; 59 5
; 59 6
; 59 11
; 59 7
; 59 8
; 59 5
; 59 10
; 59 6
; 59 8
. 46 9
¡ 161 1
! 33 11
; 59 9
: 58 5
- 45 1
. 46 5
. 46 4
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 7
. 46 9
. 46 8
- 45 1
. 46 5
- 45 1
- 45 1
- 45 8
; 59 6
. 46 5
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
: 58 9
. 46 8
- 45 1
- 45 1
- 45 7
: 58 10
. 46 9
; 59 11
. 46 11
. 46 9
. 46 6
. 46 8
: 58 8
. 46 10
: 58 5
- 45 1
. 46 9
- 45 1
¡ 161 2
! 33 4
- 45 1
- 45 7
; 59 8
- 45 1
- 45 1
- 45 8
; 59 5
. 46 7
- 45 1
- 45 1
- 45 7
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
. 46 7
; 59 9
. 46 10
. 46 10
; 59 4
. 46 9
. 46 7
: 58 5
- 45 1
; 59 9
. 46 9
- 45 1
- 45 1
- 45 12
. 46 7
. 46 9
: 58 5
- 45 1
; 59 11
. 46 8
. 46 6
; 59 8
; 59 7
. 46 10
. 46 7
. 46 9
: 58 4
- 45 1
. 46 5
: 58 9
. 46 9
: 58 7
- 45 1
; 59 9
. 46 9
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 7
. 46 8
. 46 11
- 45 1
- 45 1
- 45 8
. 46 10
- 45 1
- 45 1
- 45 11
; 59 7
; 59 11
; 59 7
. 46 8
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
. 46 10
- 45 1
- 45 1
- 45 8
; 59 7
. 46 7
. 46 9
- 45 1
- 45 1
- 45 10
; 59 5
; 59 8
. 46 10
. 46 1
- 45 1
. 46 7
; 59 7
. 46 11
. 46 7
. 46 8
. 46 9
: 58 5
- 45 1
. 46 9
. 46 7
. 46 9
. 46 10
. 46 8
. 46 5
: 58 8
- 45 1
. 46 9
: 58 6
; 59 6
. 46 4
. 46 8
. 46 9
; 59 6
. 46 7
; 59 12
. 46 10
- 45 1
- 45 1
- 45 8
- 45 1
- 45 1
- 45 7
. 46 5
- 45 1
- 45 1
- 45 8
; 59 10
. 46 9
. 46 7
; 59 8
. 46 7
: 58 5
- 45 1
; 59 10
. 46 9
; 59 6
; 59 7
: 58 5
- 45 1
. 46 6
- 45 1
- 45 1
- 45 7
; 59 8
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
. 46 12
- 45 1
- 45 1
- 45 7
. 46 6
: 58 5
. 46 8
; 59 10
. 46 5
- 45 1
; 59 10
. 46 9
« 171 1
. 46 7
. 46 8
. 46 9
» 187 10
« 171 1
» 187 7
. 46 12
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
« 171 2
- 45 1
- 45 7
; 59 5
; 59 9
; 59 5
. 46 5
. 46 6
. 46 7
» 187 8
- 45 1
- 45 1
- 45 8
: 58 6
. 46 5
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
« 171 2
- 45 1
- 45 7
» 187 4
. 46 5
- 45 1
- 45 1
. 46 8
. 46 10
; 59 7
. 46 6
: 58 5
- 45 1
: 58 5
« 171 1
» 187 5
. 46 6
. 46 6
. 46 6
- 45 1
- 45 1
- 45 7
. 46 8
- 45 1
¡ 161 2
! 33 7
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 7
. 46 5
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 7
. 46 9
- 45 1
- 45 1
- 45 8
. 46 9
: 58 6
. 46 8
- 45 1
- 45 1
- 45 7
. 46 8
- 45 1
- 45 1
- 45 8
. 46 5
. 46 5
: 58 5
; 59 4
; 59 8
. 46 11
. 46 13
; 59 6
: 58 5
- 45 1
¡ 161 2
! 33 5
; 59 6
. 46 7
. 46 11
: 58 5
- 45 1
. 46 10
: 58 5
- 45 1
; 59 7
. 46 6
« 171 1
» 187 8
. 46 6
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 4
. 46 12
- 45 1
. 46 6
; 59 1
. 46 8
- 45 1
- 45 1
- 45 7
. 46 9
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
- 45 1
- 45 7
; 59 8
. 46 5
. 46 6
. 46 8
- 45 1
- 45 1
- 45 8
; 59 6
. 46 11
. 46 7
. 46 6
. 46 6
: 58 7
- 45 1
; 59 6
. 46 9
. 46 7
¡ 161 1
! 33 6
- 45 1
- 45 1
- 45 8
. 46 8
. 46 4
. 46 3
; 59 6
: 58 4
; 59 8
: 58 5
- 45 1
. 46 8
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
- 45 4
: 58 7
. 46 11
- 45 1
- 45 1
- 45 7
. 46 8
. 46 7
. 46 6
- 45 1
- 45 1
- 45 8
. 46 10
: 58 5
- 45 1
: 58 8
. 46 14
. 46 6
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
. 46 6
- 45 1
- 45 1
- 45 8
. 46 9
. 46 5
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
. 46 8
. 46 12
: 58 5
- 45 1
. 46 7
- 45 1
- 45 1
- 45 8
. 46 9
- 45 1
- 45 1
- 45 8
. 46 6
- 45 1
- 45 1
- 45 8
. 46 8
- 45 1
- 45 1
- 45 8
. 46 5
- 45 1
- 45 1
. 46 8
: 58 5
- 45 1
. 46 9
; 59 9
. 46 6
; 59 10
. 46 7
- 45 1
- 45 1
. 46 8
; 59 6
: 58 5
- 45 1
. 46 8
- 45 1
- 45 1
- 45 8
. 46 11
- 45 1
- 45 1
- 45 8
. 46 9
; 59 6
. 46 6
; 59 6
; 59 8
: 58 5
- 45 1
. 46 8
- 45 1
- 45 1
- 45 6
̈ 776 6
. 46 11
- 45 1
- 45 1
- 45 8
. 46 7
. 46 10
- 45 1
- 45 1
- 45 8
. 46 7
; 59 7
. 46 8
: 58 5
. 46 1
. 46 10
: 58 7
. 46 9
- 45 1
- 45 1
- 45 6
; 59 6
; 59 6
. 46 5
; 59 8
. 46 8
: 58 7
- 45 1
; 59 1
. 46 8
: 58 10
; 59 6
: 58 4
. 46 8
. 46 7
. 46 7
. 46 1
: 58 9
- 45 1
. 46 4
; 59 11
: 58 6
. 46 9
- 45 1
- 45 1
- 45 7
; 59 6
. 46 7
- 45 1
- 45 1
- 45 8
: 58 11
; 59 7
. 46 8
. 46 6
- 45 7
- 45 1
- 45 7
. 46 5
; 59 9
; 59 8
. 46 6
. 46 8
. 46 9
. 46 8
. 46 9
. 46 9
; 59 6
. 46 7
; 59 10
. 46 7
; 59 4
: 58 5
- 45 1
¡ 161 2
! 33 9
. 46 11
. 46 4
. 46 9
: 58 5
- 45 1
. 46 6
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
- 45 1
- 45 8
; 59 4
. 46 9
: 58 7
. 46 9
. 46 6
. 46 6
: 58 7
. 46 9
- 45 1
- 45 1
- 45 7
. 46 5
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 7
. 46 5
- 45 1
- 45 1
- 45 8
; 59 7
. 46 5
- 45 1
- 45 1
- 45 7
- 45 1
- 45 1
- 45 8
. 46 7
. 46 9
. 46 7
- 45 1
- 45 1
- 45 7
. 46 10
: 58 5
- 45 1
. 46 6
- 45 1
- 45 1
. 46 7
- 45 1
- 45 1
. 46 8
- 45 1
- 45 1
- 45 7
. 46 7
- 45 1
- 45 1
. 46 8
: 58 7
. 46 7
¡ 161 1
! 33 8
; 59 3
. 46 8
: 58 6
. 46 6
. 46 6
: 58 8
- 45 1
. 46 7
; 59 3
. 46 6
: 58 7
. 46 7
. 46 9
. 46 9
- 45 1
- 45 8
. 46 9
. 46 9
; 59 7
. 46 7
. 46 11
. 46 8
- 45 1
- 45 1
- 45 7
. 46 9
. 46 10
- 45 1
- 45 1
- 45 7
. 46 7
; 59 10
: 58 11
. 46 9
: 58 11
- 45 1
; 59 10
. 46 7
. 46 7
: 58 5
- 45 1
; 59 1
. 46 14
- 45 1
- 45 1
- 45 8
. 46 8
. 46 7
. 46 8
- 45 1
- 45 8
. 46 10
; 59 6
: 58 5
- 45 1
. 46 9
; 59 8
. 46 8
. 46 7
: 58 5
- 45 1
; 59 9
. 46 9
. 46 10
: 58 9
- 45 1
. 46 6
: 58 7
- 45 1
; 59 9

['miguel',
 '<MA><1>',
 'de',
 'cervantes',
 '<MA><1>',
 'saavedra',
 '<MA><1>',
 'el',
 '<MA><1>',
 'ingenioso',
 'hidalgo',
 'don',
 'quijote',
 '<MA><1>',
 'de',
 'la',
 'mancha',
 '<MA><1>',
 'al',
 '<MA><1>',
 'duque',
 '<MA><1>',
 'de',
 'bejar',
 '<MA><1><AC><3>',
 'marques',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><AC><7><MA><8>',
 'de',
 '<MA><1><MA><2>',
 'gibraleon',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><AC><9><MA><10><PC><11>',
 'conde',
 '<MA><1><MA><2><MA><3><MA><4><MA><5>',
 'de',
 '<MA><1><MA><2>',
 'benalcazar',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><AC><8><MA><9><MA><10><MA><11>',
 'y',
 '<MA><1>',
 'banares',
 '<MA><1><MA><2><MA><3><TI><4><MA><5><MA><6><MA><7><MA><8><PC><9>',
 'vizconde',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8>',
 'de',
 '<MA><1><MA><2>',
 'la',
 '<MA><1><MA><2>',
 'puebla',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>',
 'de',
 '<MA><1><MA><2>',
 'alcocersenor',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8><MA><9><MA><10><MA><11><TI><12><MA><13><MA><14>',
 'de',
 '<MA><1><MA><2>',
 'las',
 '<MA><1><MA><2><MA><3>',
 'villas',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>',
 'de',
 '<MA><1><MA><2>',
 'capilla',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8>',
 'curiel',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>',
 'y',
 '<MA><1>',
 'burguillos',
 '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><MA><9><MA><10>',
 'en',
 '<MA><1>',
 'fe',
 'del',
 'buen',
 'acogimiento',
 'y',
 'honra',
 'que',
 'hace',
 'vuestra',
 '<MA><1>',
 'excelencia',
 '<MA><1>',
 'a',
 'toda',
 'suerte',
 'de',
 'libros',
 '<PC><7>',
 'como',
 'principe',
 '<AC><4>',
 'tan',
 'inclinado',
 'a',
 'favorecer',
 'las',
 'buenas',
 'artes',
 '<PC><6>',
 'mayormente',
 'las',
 'que',
 'por',
 'su',
 'nobleza',
 'no',
 'se',
 'abaten',
 'al',
 'servicio',
 'y',
 'granjerias',
 '<AC><9>',
 'del',
 'vulgo',
 '<PC><6>',
 'he',
 'determinado',
 'de',
 'sacar',
 'a',
 'luz',
 'al',
 'ingenioso',
 '<MA><1>',
 'hidalgo',
 'don',
 'quijote',
 '<MA><1>',
 'de',
 'la',
 'mancha',
 '<MA><1>',
 'al',
 'abrigo',
 'del',
 'clarisimo',
 '<AC><6>',
 'nombre',
 'de',
 'vuestra',
 '<MA><1>',
 'excelencia',
 '<MA><1><PC><11>',
 'a',
 'quien',
 '<PC><6>',
 'con',
 'el',
 'acatamiento',
 'que',
 'debo',
 'a',
 'tanta',
 'grandeza',
 '<PC><9>',
 'suplico',
 'le',
 'reciba',
 'agradablemente',
 'en',
 'su',
 'proteccion',
 '<AC><10><PC><12>',
 'para',
 'que',
 'a',
 'su',
 'sombra',
 '<PC><7>',
 'aunque',
 'desnudo',
 'de',
 'aquel',
 'precioso',
 'ornamento',
 'de',
 'elegancia',
 'y',
 'erudicion',
 '<AC><9>',
 'de',
 'que',
 'suelen',
 'andar',
 'vestidas',
 'las',
 'obras',
 'que',
 'se',
 'componen',
 'en',
 'las',
 'casas',
 'de',
 'los',
 'hombres',
 'que',
 'saben',
 '<PC><6>',
 'ose',
 'parecer',
 'seguramente',
 'en',
 'el',
 'juicio',
 'de',
 'algunos',
 'que',
 '<PC><4>',
 'no',
 'continiendose',
 '<AC><9>',
 'en',
 'los',
 'limites',
 '<AC><3>',
 'de',
 'su',
 'ignorancia',
 '<PC><11>',
 'suelen',
 'condenar',
 'con',
 'mas',
 '<AC><3>',
 'rigor',
 'y',
 'menos',
 'justicia',
 'los',
 'trabajos',
 'ajenos',
 '<ND>',
 'que',
 '<PC><4>',
 'poniendo',
 'los',
 'ojos',
 'la',
 'prudencia',
 'de',
 'vuestra',
 '<MA><1>',
 'excelencia',
 '<MA><1>',
 'en',
 'mi',
 'buen',
 'deseo',
 '<PC><6>',
 'fio',
 '<AC><3>',
 'que',
 'no',
 'desdenara',
 '<TI><7><AC><11>',
 'la',
 'cortedad',
 'de',
 'tan',
 'humilde',
 'servicio',
 '<ND>',
 'miguel',
 '<MA><1>',
 'de',
 'cervantes',
 '<MA><1>',
 'saavedra',
 '<MA><1>',
 'prologo',
 '<MA><1><AC><4>',
 'desocupado',
 '<MA><1>',
 'lector',
 '<ND>',
 'sin',
 'juramento',
 'me',
 'podras',
 '<AC><6>',
 'creer',
 'que',
 'quisiera',
 'que',
 'este',
 'libro',
 '<PC><6>',
 'como',
 'hijo',
 'del',
 'entendimiento',
 '<PC><14>',
 'fuera',
 'el',
 'mas',
 '<AC><3>',
 'hermoso',
 '<PC><8>',
 'el',
 'mas',
 '<AC><3>',
 'gallardo',
 'y',
 'mas',
 '<AC><3>',
 'discreto',
 'que',
 'pudiera',
 'imaginarse',
 '<ND>',
 'pero',
 '<MA><1>',
 'no',
 'he',
 'podido',
 'yo',
 'contravenir',
 'al',
 'orden',
 'de',
 'naturaleza',
 '<PC><11>',
 'que',
 'en',
 'ella',
 'cada',
 'cosa',
 'engendra',
 'su',
 'semejante',
 '<ND>',
 'y',
 '<MA><1><PC><2>',
 'asi',
 '<AC><4><PC><5>',
 'que',
 '<IA><1><AC><5>',
 'podia',
 '<AC><5>',
 'engendrar',
 'el',
 'esteril',
 '<AC><5>',
 'y',
 'mal',
 'cultivado',
 'ingenio',
 'mio',
 '<AC><3><PC><5>',
 'sino',
 'la',
 'historia',
 'de',
 'un',
 'hijo',
 'seco',
 '<PC><5>',
 'avellanado',
 '<PC><11>',
 'antojadizo',
 'y',
 'lleno',
 'de',
 'pensamientos',
 'varios',
 'y',
 'nunca',
 'imaginados',
 'de',
 'otro',
 'alguno',
 '<PC><7>',
 'bien',
 'como',
 'quien',
 'se',
 'engendro',
 '<AC><9>',
 'en',
 'una',
 'carcel',
 '<AC><3><PC><8>',
 'donde',
 'toda',
 'incomodidad',
 'tiene',
 'su',
 'asiento',
 'y',
 'donde',
 'todo',
 'triste',
 'ruido',
 'hace',
 'su',
 'habitacion',
 '<AC><10><IC><12>',
 'el',
 '<MA><1>',
 'sosiego',
 '<PC><8>',
 'el',
 'lugar',
 'apacible',
 '<PC><9>',
 'la',
 'amenidad',
 'de',
 'los',
 'campos',
 '<PC><7>',
 'la',
 'serenidad',
 'de',
 'los',
 'cielos',
 '<PC><7>',
 'el',
 'murmurar',
 'de',
 'las',
 'fuentes',
 '<PC><8>',
 'la',
 'quietud',
 'del',
 'espiritu',
 '<AC><5>',
 'son',
 'grande',
 'parte',
 'para',
 'que',
 'las',
 'musas',
 'mas',
 '<AC><3>',
 'esteriles',
 '<AC><5>',
 'se',
 'muestren',
 'fecundas',
 'y',
 'ofrezcan',
 'partos',
 'al',
 'mundo',
 'que',
 'le',
 'colmen',
 'de',
 'maravilla',
 'y',
 'de',
 'contento',
 '<ND>',
 'acontece',
 '<MA><1>',
 'tener',
 'un',
 'padre',
 'un',
 'hijo',
 'feo',
 'y',
 'sin',
 'gracia',
 'alguna',
 '<PC><7>',
 'y',
 'el',
 'amor',
 'que',
 'le',
 'tiene',
 'le',
 'pone',
 'una',
 'venda',
 'en',
 'los',
 'ojos',
 'para',
 'que',
 'no',
 'vea',
 'sus',
 'faltas',
 '<PC><7>',
 'antes',
 'las',
 'juzga',
 'por',
 'discreciones',
 'y',
 'lindezas',
 'y',
 'las',
 'cuenta',
 'a',
 'sus',
 'amigos',
 'por',
 'agudezas',
 'y',
 'donaires',
 '<ND>',
 'pero',
 '<MA><1>',
 'yo',
 '<PC><3>',
 'que',
 '<PC><4>',
 'aunque',
 'parezco',
 'padre',
 '<PC><6>',
 'soy',
 'padrastro',
 'de',
 'don',
 'quijote',
 '<MA><1><PC><8>',
 'no',
 'quiero',
 'irme',
 'con',
 'la',
 'corriente',
 'del',
 'uso',
 '<PC><4>',
 'ni',
 'suplicarte',
 'casi',
 'con',
 'las',
 'lagrimas',
 '<AC><3>',
 'en',
 'los',
 'ojos',
 '<PC><5>',
 'como',
 'otros',
 'hacen',
 '<PC><6>',
 'lector',
 'carisimo',
 '<AC><5><PC><10>',
 'que',
 'perdones',
 'o',
 'disimules',
 'las',
 'faltas',
 'que',
 'en',
 'este',
 'mi',
 'hijo',
 'vieres',
 '<PC><7>',
 'que',
 'ni',
 'eres',
 'su',
 'pariente',
 'ni',
 'su',
 'amigo',
 '<PC><6>',
 'y',
 'tienes',
 'tu',
 'alma',
 'en',
 'tu',
 'cuerpo',
 'y',
 'tu',
 'libre',
 'albedrio',
 '<AC><8>',
 'como',
 'el',
 'mas',
 '<AC><3>',
 'pintado',
 '<PC><8>',
 'y',
 'estas',
 '<AC><5>',
 'en',
 'tu',
 'casa',
 '<PC><5>',
 'donde',
 'eres',
 'senor',
 '<TI><4>',
 'della',
 '<PC><6>',
 'como',
 'el',
 'rey',
 'de',
 'sus',
 'alcabalas',
 '<PC><10>',
 'y',
 'sabes',
 'lo',
 'que',
 'comunmente',
 '<AC><5>',
 'se',
 'dice',
 '<PC><5>',
 'que',
 'debajo',
 '<ND>',
 'de',
 'mi',
 'manto',
 '<PC><6>',
 'al',
 'rey',
 'mato',
 '<ND><PC><2>',
 'todo',
 'lo',
 'cual',
 'te',
 'esenta',
 'y',
 'hace',
 'libre',
 'de',
 'todo',
 'respecto',
 'y',
 'obligacion',
 '<AC><10><PC><12>',
 'y',
 '<PC><2>',
 'asi',
 '<AC><4><PC><5>',
 'puedes',
 'decir',
 'de',
 'la',
 'historia',
 'todo',
 'aquello',
 'que',
 'te',
 'pareciere',
 '<PC><10>',
 'sin',
 'temor',
 'que',
 'te',
 'calunien',
 'por',
 'el',
 'mal',
 'ni',
 'te',
 'premien',
 'por',
 'el',
 'bien',
 'que',
 'dijeres',
 'della',
 '<ND>',
 'solo',
 '<MA><1>',
 'quisiera',
 'dartela',
 '<AC><3>',
 'monda',
 'y',
 'desnuda',
 '<PC><8>',
 'sin',
 'el',
 'ornato',
 'de',
 'prologo',
 '<AC><4><PC><9>',
 'ni',
 'de',
 'la',
 'inumerabilidad',
 'y',
 'catalogo',
 '<AC><5>',
 'de',
 'los',
 'acostumbrados',
 'sonetos',
 '<PC><8>',
 'epigramas',
 'y',
 'elogios',
 'que',
 'al',
 'principio',
 'de',
 'los',
 'libros',
 'suelen',
 'ponerse',
 '<ND>',
 'porque',
 '<MA><1>',
 'te',
 'se',
 '<AC><3>',
 'decir',
 'que',
 '<PC><4>',
 'aunque',
 'me',
 'costo',
 '<AC><6>',
 'algun',
 '<AC><5>',
 'trabajo',
 'componerla',
 '<PC><11>',
 'ninguno',
 'tuve',
 'por',
 'mayor',
 'que',
 'hacer',
 'esta',
 'prefacion',
 '<AC><9>',
 'que',
 'vas',
 'leyendo',
 '<ND>',
 'muchas',
 '<MA><1>',
 'veces',
 'tome',
 '<AC><5>',
 'la',
 'pluma',
 'para',
 'escribille',
 '<PC><11>',
 'y',
 'muchas',
 'la',
 'deje',
 '<AC><5><PC><6>',
 'por',
 'no',
 'saber',
 'lo',
 'que',
 'escribiria',
 '<AC><10><ND>',
 'y',
 'estando',
 'una',
 'suspenso',
 '<PC><9>',
 'con',
 'el',
 'papel',
 'delante',
 '<PC><8>',
 'la',
 'pluma',
 'en',
 'la',
 'oreja',
 '<PC><6>',
 'el',
 'codo',
 'en',
 'el',
 'bufete',
 'y',
 'la',
 'mano',
 'en',
 'la',
 'mejilla',
 '<PC><8>',
 'pensando',
 'lo',
 'que',
 'diria',
 '<AC><5><PC><7>',
 'entro',
 '<AC><6>',
 'a',
 'deshora',
 'un',
 'amigo',
 'mio',
 '<AC><3><PC><5>',
 'gracioso',
 'y',
 'bien',
 'entendido',
 '<PC><10>',
 'el',
 'cual',
 '<PC><5>',
 'viendome',
 '<AC><4>',
 'tan',
 'imaginativo',
 '<PC><12>',
 'me',
 'pregunto',
 '<AC><9>',
 'la',
 'causa',
 '<PC><6>',
 'y',
 '<PC><2>',
 'no',
 'encubriendosela',
 '<AC><9>',
 'yo',
 '<PC><3>',
 'le',
 'dije',
 'que',
 'pensaba',
 'en',
 'el',
 'prologo',
 '<AC><4>',
 'que',
 'habia',
 '<AC><5>',
 'de',
 'hacer',
 'a',
 'la',
 'historia',
 'de',
 'don',
 'quijote',
 '<MA><1><PC><8>',
 'y',
 'que',
 'me',
 'tenia',
 '<AC><5>',
 'de',
 'suerte',
 'que',
 'ni',
 'queria',
 '<AC><6>',
 'hacerle',
 '<PC><8>',
 'ni',
 'menos',
 'sacar',
 'a',
 'luz',
 'las',
 'hazanas',
 '<TI><6>',
 'de',
 'tan',
 'noble',
 'caballero',
 '<ND>',
 'porque',
 '<ND><MA><2>',
 'como',
 '<IA><1><AC><4>',
 'quereis',
 '<AC><6>',
 'vos',
 'que',
 'no',
 'me',
 'tenga',
 'confuso',
 'el',
 'que',
 '<AC><4>',
 'dira',
 '<AC><5>',
 'el',
 'antiguo',
 'legislador',
 'que',
 'llaman',
 'vulgo',
 'cuando',
 'vea',
 'que',
 '<PC><4>',
 'al',
 'cabo',
 'de',
 'tantos',
 'anos',
 '<TI><3>',
 'como',
 'ha',
 'que',
 'duermo',
 'en',
 'el',
 'silencio',
 'del',
 'olvido',
 '<PC><7>',
 'salgo',
 'ahora',
 '<PC><6>',
 'con',
 'todos',
 'mis',
 'anos',
 '<TI><3>',
 'a',
 'cuestas',
 '<PC><8>',
 'con',
 'una',
 'leyenda',
 'seca',
 'como',
 'un',
 'esparto',
 '<PC><8>',
 'ajena',
 'de',
 'invencion',
 '<AC><9><PC><11>',
 'menguada',
 'de',
 'estilo',
 '<PC><7>',
 'pobre',
 'de',
 'concetos',
 'y',
 'falta',
 'de',
 'toda',
 'erudicion',
 '<AC><9>',
 'y',
 'doctrina',
 '<PC><9>',
 'sin',
 'acotaciones',
 'en',
 'las',
 'margenes',
 '<AC><3>',
 'y',
 'sin',
 'anotaciones',
 'en',
 'el',
 'fin',
 'del',
 'libro',
 '<PC><6>',
 'como',
 'veo',
 'que',
 'estan',
 '<AC><5>',
 'otros',
 'libros',
 '<PC><7>',
 'aunque',
 'sean',
 'fabulosos',
 'y',
 'profanos',
 '<PC><9>',
 'tan',
 'llenos',
 'de',
 'sentencias',
 'de',
 ...]

In [11]:
quijote_corpus_diccionario_token_frecuencias = {}
quijote_corpus_diccionario_token_indices = {}

indice = 1
for token in quijote_corpus_tokens:
    if not token in quijote_corpus_diccionario_token_frecuencias:
        quijote_corpus_diccionario_token_frecuencias[token] = 1
        quijote_corpus_diccionario_token_indices[token] = indice
        indice += 1
    else:
        quijote_corpus_diccionario_token_frecuencias[token] += 1

quijote_corpus_diccionario_token_frecuencias, quijote_corpus_diccionario_token_indices

({'miguel': 4,
  '<MA><1>': 6304,
  'de': 11503,
  'cervantes': 3,
  'saavedra': 4,
  'el': 5971,
  'ingenioso': 12,
  'hidalgo': 34,
  'don': 1711,
  'quijote': 1444,
  'la': 6490,
  'mancha': 114,
  'al': 1148,
  'duque': 151,
  'bejar': 2,
  '<MA><1><AC><3>': 118,
  'marques': 11,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><AC><7><MA><8>': 2,
  '<MA><1><MA><2>': 40,
  'gibraleon': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><AC><9><MA><10><PC><11>': 1,
  'conde': 13,
  '<MA><1><MA><2><MA><3><MA><4><MA><5>': 34,
  'benalcazar': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><AC><8><MA><9><MA><10><MA><11>': 1,
  'y': 11392,
  'banares': 1,
  '<MA><1><MA><2><MA><3><TI><4><MA><5><MA><6><MA><7><MA><8><PC><9>': 1,
  'vizconde': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8>': 3,
  'puebla': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>': 34,
  'alcocersenor': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8><MA><9><MA><10><MA><11><TI><12><MA><13><MA><14>': 1,
  'las': 2217,
  '<MA><1><MA><2><MA><3>': 33,
  'villas': 1,
  'capilla': 5,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8>': 1,
  'curiel': 1,
  'burguillos': 1,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><MA><9><MA><10>': 2,
  'en': 5197,
  'fe': 56,
  'del': 1655,
  'buen': 284,
  'acogimiento': 8,
  'honra': 52,
  'que': 13250,
  'hace': 103,
  'vuestra': 517,
  'excelencia': 25,
  'a': 6058,
  'toda': 206,
  'suerte': 84,
  'libros': 84,
  '<PC><7>': 2738,
  'como': 1577,
  'principe': 11,
  '<AC><4>': 1335,
  'tan': 775,
  'inclinado': 5,
  'favorecer': 11,
  'buenas': 57,
  'artes': 5,
  '<PC><6>': 2920,
  'mayormente': 1,
  'por': 2428,
  'su': 2034,
  'nobleza': 7,
  'no': 3878,
  'se': 3150,
  'abaten': 2,
  'servicio': 21,
  'granjerias': 1,
  '<AC><9>': 646,
  'vulgo': 16,
  'he': 316,
  'determinado': 19,
  'sacar': 26,
  'luz': 43,
  'abrigo': 2,
  'clarisimo': 2,
  '<AC><6>': 1923,
  'nombre': 135,
  '<MA><1><PC><11>': 143,
  'quien': 556,
  'con': 2614,
  'acatamiento': 1,
  'debo': 18,
  'tanta': 91,
  'grandeza': 39,
  '<PC><9>': 1719,
  'suplico': 20,
  'le': 2115,
  'reciba': 4,
  'agradablemente': 1,
  'proteccion': 1,
  '<AC><10><PC><12>': 78,
  'para': 841,
  'sombra': 19,
  'aunque': 323,
  'desnudo': 23,
  'aquel': 331,
  'precioso': 4,
  'ornamento': 1,
  'elegancia': 1,
  'erudicion': 3,
  'suelen': 37,
  'andar': 47,
  'vestidas': 4,
  'obras': 35,
  'componen': 7,
  'casas': 21,
  'los': 3023,
  'hombres': 65,
  'saben': 14,
  'ose': 1,
  'parecer': 116,
  'seguramente': 8,
  'juicio': 52,
  'algunos': 74,
  '<PC><4>': 891,
  'continiendose': 1,
  'limites': 10,
  '<AC><3>': 3434,
  'ignorancia': 9,
  '<PC><11>': 654,
  'condenar': 2,
  'mas': 1426,
  'rigor': 17,
  'menos': 221,
  'justicia': 35,
  'trabajos': 23,
  'ajenos': 6,
  '<ND>': 7139,
  'poniendo': 11,
  'ojos': 173,
  'prudencia': 14,
  'mi': 1355,
  'deseo': 98,
  'fio': 5,
  'desdenara': 1,
  '<TI><7><AC><11>': 1,
  'cortedad': 1,
  'humilde': 14,
  'prologo': 7,
  '<MA><1><AC><4>': 107,
  'desocupado': 3,
  'lector': 7,
  'sin': 720,
  'juramento': 20,
  'me': 1444,
  'podras': 4,
  'creer': 36,
  'quisiera': 48,
  'este': 495,
  'libro': 59,
  'hijo': 57,
  'entendimiento': 44,
  '<PC><14>': 92,
  'fuera': 167,
  'hermoso': 13,
  '<PC><8>': 2196,
  'gallardo': 11,
  'discreto': 49,
  'pudiera': 56,
  'imaginarse': 7,
  'pero': 621,
  'podido': 12,
  'yo': 1312,
  'contravenir': 4,
  'orden': 53,
  'naturaleza': 20,
  'ella': 321,
  'cada': 152,
  'cosa': 280,
  'engendra': 2,
  'semejante': 23,
  '<MA><1><PC><2>': 47,
  'asi': 661,
  '<AC><4><PC><5>': 282,
  '<IA><1><AC><5>': 71,
  'podia': 109,
  '<AC><5>': 4836,
  'engendrar': 3,
  'esteril': 5,
  'mal': 273,
  'cultivado': 1,
  'ingenio': 27,
  'mio': 111,
  '<AC><3><PC><5>': 243,
  'sino': 454,
  'historia': 169,
  'un': 1254,
  'seco': 15,
  '<PC><5>': 2050,
  'avellanado': 2,
  'antojadizo': 1,
  'lleno': 38,
  'pensamientos': 62,
  'varios': 1,
  'nunca': 92,
  'imaginados': 3,
  'otro': 318,
  'alguno': 84,
  'bien': 647,
  'engendro': 4,
  'una': 851,
  'carcel': 11,
  '<AC><3><PC><8>': 47,
  'donde': 456,
  'incomodidad': 3,
  'tiene': 230,
  'asiento': 10,
  'todo': 723,
  'triste': 65,
  'ruido': 31,
  'habitacion': 2,
  '<AC><10><IC><12>': 2,
  'sosiego': 14,
  'lugar': 199,
  'apacible': 8,
  'amenidad': 2,
  'campos': 13,
  'serenidad': 2,
  'cielos': 16,
  'murmurar': 2,
  'fuentes': 8,
  'quietud': 5,
  'espiritu': 11,
  'son': 307,
  'grande': 119,
  'parte': 214,
  'musas': 2,
  'esteriles': 2,
  'muestren': 3,
  'fecundas': 1,
  'ofrezcan': 1,
  'partos': 2,
  'mundo': 237,
  'colmen': 1,
  'maravilla': 14,
  'contento': 77,
  'acontece': 4,
  'tener': 161,
  'padre': 144,
  'feo': 5,
  'gracia': 20,
  'alguna': 251,
  'amor': 72,
  'pone': 21,
  'venda': 4,
  'vea': 35,
  'sus': 639,
  'faltas': 8,
  'antes': 171,
  'juzga': 5,
  'discreciones': 4,
  'lindezas': 2,
  'cuenta': 133,
  'amigos': 41,
  'agudezas': 2,
  'donaires': 7,
  '<PC><3>': 227,
  'parezco': 4,
  'soy': 225,
  'padrastro': 3,
  '<MA><1><PC><8>': 594,
  'quiero': 148,
  'irme': 4,
  'corriente': 6,
  'uso': 33,
  'ni': 860,
  'suplicarte': 1,
  'casi': 59,
  'lagrimas': 43,
  'otros': 192,
  'hacen': 52,
  'carisimo': 2,
  '<AC><5><PC><10>': 29,
  'perdones': 1,
  'o': 751,
  'disimules': 1,
  'vieres': 4,
  'eres': 58,
  'pariente': 4,
  'amigo': 166,
  'tienes': 40,
  'tu': 394,
  'alma': 95,
  'cuerpo': 87,
  'libre': 38,
  'albedrio': 5,
  '<AC><8>': 1014,
  'pintado': 18,
  'estas': 191,
  'casa': 211,
  'senor': 670,
  '<TI><4>': 1100,
  'della': 73,
  'rey': 78,
  'alcabalas': 1,
  '<PC><10>': 1146,
  'sabes': 30,
  'lo': 2113,
  'comunmente': 5,
  'dice': 152,
  'debajo': 52,
  'manto': 4,
  'mato': 7,
  '<ND><PC><2>': 19,
  'cual': 458,
  'te': 457,
  'esenta': 1,
  'respecto': 2,
  'obligacion': 8,
  '<PC><2>': 508,
  'puedes': 15,
  'decir': 335,
  'aquello': 64,
  'pareciere': 4,
  'temor': 37,
  'calunien': 1,
  'premien': 1,
  'dijeres': 4,
  'solo': 181,
  'dartela': 3,
  'monda': 1,
  'desnuda': 4,
  'ornato': 1,
  '<AC><4><PC><9>': 42,
  'inumerabilidad': 1,
  'catalogo': 2,
  'acostumbrados': 2,
  'sonetos': 5,
  'epigramas': 2,
  'elogios': 2,
  'principio': 31,
  'ponerse': 25,
  'porque': 872,
  'costo': 5,
  'algun': 183,
  'trabajo': 59,
  'componerla': 1,
  'ninguno': 53,
  'tuve': 20,
  'mayor': 95,
  'hacer': 313,
  'esta': 716,
  'prefacion': 1,
  'vas': 16,
  'leyendo': 9,
  'muchas': 143,
  'veces': 124,
  'tome': 30,
  'pluma': 9,
  'escribille': 1,
  'deje': 35,
  '<AC><5><PC><6>': 110,
  'saber': 154,
  'escribiria': 1,
  '<AC><10><ND>': 82,
  'estando': 59,
  'suspenso': 22,
  'papel': 13,
  'delante': 71,
  'oreja': 10,
  'codo': 1,
  'bufete': 1,
  'mano': 189,
  'mejilla': 1,
  'pensando': 12,
  'diria': 6,
  '<AC><5><PC><7>': 215,
  'entro': 46,
  'deshora': 12,
  'gracioso': 19,
  'entendido': 15,
  'viendome': 4,
  'imaginativo': 1,
  '<PC><12>': 282,
  'pregunto': 86,
  'causa': 81,
  'encubriendosela': 1,
  'dije': 39,
  'pensaba': 41,
  'habia': 636,
  'tenia': 216,
  'queria': 69,
  'hacerle': 20,
  'hazanas': 43,
  '<TI><6>': 120,
  'noble': 11,
  'caballero': 440,
  '<ND><MA><2>': 1365,
  '<IA><1><AC><4>': 17,
  'quereis': 18,
  'vos': 138,
  'tenga': 46,
  'confuso': 17,
  'dira': 15,
  'antiguo': 10,
  'legislador': 3,
  'llaman': 56,
  'cuando': 524,
  'cabo': 47,
  'tantos': 67,
  'anos': 91,
  '<TI><3>': 101,
  'ha': 639,
  'duermo': 4,
  'silencio': 53,
  'olvido': 15,
  'salgo': 6,
  'ahora': 226,
  'todos': 501,
  'mis': 250,
  'cuestas': 8,
  'leyenda': 7,
  'seca': 4,
  'esparto': 3,
  'ajena': 12,
  'invencion': 14,
  '<AC><9><PC><11>': 69,
  'menguada': 4,
  'estilo': 10,
  'pobre': 72,
  'concetos': 2,
  'falta': 46,
  'doctrina': 5,
  'acotaciones': 2,
  'margenes': 3,
  'anotaciones': 3,
  'fin': 129,
  'veo': 36,
  'estan': 70,
  'sean': 44,
  'fabulosos': 2,
  'profanos': 1,
  'llenos': 12,
  'sentencias': 17,
  'aristoteles': 4,
  '<MA><1><AC><7><PC><13>': 6,
  'platon': 2,
  '<MA><1><AC><6>': 311,
  'caterva': 10,
  'filosofos': 2,
  '<AC><5><PC><11>': 32,
  'admiran': 2,
  'leyentes': 2,
  'tienen': 97,
  'autores': 18,
  'leidos': 2,
  '<AC><4><PC><8>': 11,
  'eruditos': 1,
  'elocuentes': 2,
  '<IC><11>': 19,
  'pues': 529,
  '<IA><1><AC><5><PC><6>': 2,
  'citan': 1,
  'divina': 8,
  'escritura': 10,
  '<MA><1><IC><10>': 1,
  'diran': 6,
  'unos': 94,
  'santos': 10,
  'tomases': 1,
  'doctores': 1,
  'iglesia': 27,
  'guardando': 7,
  'esto': 553,
  'decoro': 10,
  'renglon': 1,
  '<AC><7>': 1523,
  'han': 221,
  'enamorado': 37,
  'destraido': 2,
  'sermoncico': 1,
  'cristiano': 37,
  'es': 1323,
  'regalo': 9,
  'oille': 2,
  'leelle': 1,
  'carecer': 2,
  'tengo': 279,
  'acotar': 1,
  'margen': 7,
  'anotar': 1,
  'sigo': 4,
  '<AC><2><PC><4>': 101,
  'ponerlos': 1,
  'letras': 40,
  'abece': 2,
  '<AC><6><PC><7>': 35,
  'comenzando': 6,
  '<MA><1><AC><7>': 134,
  'acabando': 7,
  'xenofonte': 1,
  'zoilo': 1,
  'zeuxis': 1,
  '<MA><1><PC><7>': 594,
  'fue': 385,
  'maldiciente': 3,
  'uno': 232,
  'pintor': 7,
  'tambien': 159,
  'cuyos': 9,
  'duques': 30,
  'marqueses': 1,
  'condes': 3,
  'obispos': 3,
  'damas': 23,
  'poetas': 14,
  'celeberrimos': 1,
  '<AC><7><ND>': 66,
  'si': 1427,
  'pidiese': 7,
  'dos': 421,
  'tres': 159,
  'oficiales': 1,
  'darian': 2,
  '<AC><5><PC><8>': 51,
  'tales': 93,
  'les': 221,
  'igualasen': 1,
  'aquellos': 121,
  'nuestra': 78,
  'espana': 45,
  '<MA><1><TI><6><ND>': 7,
  'prosegui': 1,
  '<ND><AC><10><ND><PC><12>': 1,
  'determino': 19,
  'quede': 20,
  'sepultado': 5,
  'archivos': 2,
  'hasta': 225,
  'cielo': 159,
  'depare': 3,
  'adorne': 1,
  'tantas': 60,
  'cosas': 214,
  'faltan': 5,
  'hallo': 58,
  'incapaz': 2,
  'remediarlas': 2,
  'insuficiencia': 1,
  'pocas': 13,
  'naturalmente': 6,
  'poltron': 1,
  'perezoso': 7,
  'andarme': 3,
  'buscando': 34,
  'digan': 10,
  'ellos': 180,
  'aqui': 332,
  'nace': 7,
  'suspension': 5,
  '<AC><10>': 523,
  'elevamiento': 1,
  'hallastes': 2,
  'bastante': 15,
  'ponerme': 16,
  'habeis': 63,
  'oido': 87,
  '<AC><3><ND>': 178,
  'oyendo': 38,
  'dandose': 4,
  'palmada': 2,
  'frente': 10,
  'disparando': 1,
  'carga': 14,
  'risa': 38,
  'dijo': 1105,
  'dios': 354,
  '<MA><1><PC><5>': 190,
  'hermano': 62,
  'agora': 94,
  'acabo': 34,
  'desenganar': 1,
  '<TI><9>': 11,
  'engano': 20,
  'estado': 59,
  'mucho': 173,
  'tiempo': 188,
  'os': 299,
  'conozco': 18,
  'siempre': 104,
  'tenido': 37,
  'prudente': 12,
  'todas': 238,
  'vuestras': 52,
  'aciones': 1,
  'estais': 15,
  'lejos': 29,
  'serlo': 25,
  'tierra': 156,
  '<IA><1><MA><2><AC><4>': 14,
  'posible': 68,
  'poco': 220,
  'momento': 17,
  'faciles': 2,
  'remediar': 12,
  'puedan': 9,
  'fuerzas': 27,
  'suspender': 6,
  'absortar': 1,
  'maduro': 2,
  'vuestro': 93,
  'hecho': 163,
  'romper': 7,
  'atropellar': 1,
  'otras': 162,
  'dificultades': 8,
  'mayores': 35,
  '<IC><8>': 71,
  'habilidad': 11,
  'sobra': 4,
  'pereza': 6,
  'penuria': 1,
  'discurso': 37,
  '<IA><1><MA><2><AC><7>': 3,
  'ver': 245,
  'verdad': 256,
  'digo': 201,
  '<IC><5>': 54,
  'estadme': 2,
  'atento': 15,
  'vereis': 9,
  'abrir': 9,
  'cerrar': 14,
  'confundo': 1,
  'remedio': 56,
  'decis': 30,
  'suspenden': 5,
  'acobardan': 1,
  'dejar': 66,
  'famoso': 65,
  'espejo': 11,
  'caballeria': 93,
  'andante': 130,
  'decid': 7,
  'replique': 3,
  'decia': 113,
  '<AC><5><ND><PC><8>': 3,
  '<IA><1>': 76,
  'modo': 107,
  'pensais': 3,
  'llenar': 2,
  'vacio': 6,
  'reducir': 6,
  'claridad': 9,
  'caos': 2,
  'confusion': 16,
  '<AC><9><IC><11>': 1,
  '<AC><2>': 891,
  'primero': 107,
  'reparais': 1,
  'personajes': 6,
  'graves': 10,
  'titulo': 20,
  'puede': 191,
  'mesmo': 134,
  'tomeis': 3,
  'hacerlos': 1,
  'despues': 116,
  'podeis': 16,
  'bautizar': 1,
  'poner': 77,
  'quisieredes': 10,
  '<AC><7><PC><13>': 16,
  'ahijandolos': 1,
  'preste': 5,
  'juan': 14,
  'indias': 6,
  'emperador': 33,
  'trapisonda': 3,
  'hay': 313,
  'noticia': 39,
  'fueron': 92,
  'famosos': 20,
  'hayan': 16,
  'sido': 95,
  'hubiere': 12,
  'pedantes': 1,
  'bachilleres': 1,
  'detras': 18,
  'muerdan': 1,
  'murmuren': 1,
  'desta': 156,
  'maravedis': 5,
  'ya': 433,
  'averiguen': 1,
  'mentira': 24,
  'cortar': 5,
  'escribistes': 1,
  'citar': 2,
  'sacaredes': 1,
  'dichos': 3,
  'pusieredes': 1,
  'manera': 210,
  'venga': 42,
  'pelo': 12,
  'algunas': 58,
  'latines': 2,
  'sepais': 8,
  'memoria': 71,
  'cuesten': 1,
  'buscalle': 4,
  'sera': 130,
  'tratando': 5,
  'libertad': 48,
  'cautiverio': 3,
  'non': 9,
  'bene': 2,
  'pro': 10,
  'toto': 1,
  'libertas': 1,
  'venditur': 1,
  'auro': 1,
  'luego': 218,
  'horacio': 2,
  'trataredes': 4,
  'poder': 64,
  'muerte': 92,
  'acudir': 19,
  'pallida': 1,
  'mors': 1,
  'aequo': 1,
  'pulsat': 1,
  'pede': 1,
  'pauperum': 1,
  'tabernas': 1,
  'regumque': 1,
  'turres': 1,
  'amistad': 21,
  'manda': 17,
  'enemigo': 38,
  'entraros': 1,
  'punto': 114,
  'tantico': 1,
  'curiosidad': 8,
  'palabras': 76,
  'mismo': 112,
  '<MA><1><ND>': 779,
  'ego': 1,
  'autem': 2,
  'dico': 1,
  'vobis': 1,
  'diligite': 1,
  'inimicos': 1,
  'vestros': 1,
  '<ND><ND>': 184,
  'malos': 26,
  '<PC><13>': 152,
  'acudid': 3,
  'evangelio': 1,
  'corde': 1,
  'exeunt': 1,
  'cogitationes': 1,
  'malae': 1,
  'instabilidad': 2,
  'ahi': 37,
  'caton': 4,
  '<MA><1><AC><5><PC><7>': 9,
  'dara': 11,
  'distico': 1,
  'donec': 1,
  'eris': 2,
  'felix': 10,
  'multos': 1,
  'numerabis': 1,
  'amicos': 1,
  'tempora': 1,
  'fuerint': 1,
  'nubila': 1,
  'solus': 1,
  'estos': 153,
  'latinicos': 1,
  'tendran': 6,
  'siquiera': 20,
  'gramatico': 1,
  '<AC><6><PC><11>': 19,
  'poca': 33,
  'provecho': 34,
  'dia': 177,
  'hoy': 44,
  'toca': 30,
  'nombrais': 1,
  'gigante': 47,
  'hacelde': 1,
  'sea': 175,
  'golias': 2,
  '<MA><1><AC><5><PC><8>': 2,
  'costara': 2,
  'nada': 104,
  'teneis': 12,
  'anotacion': 4,
  'goliat': 1,
  'filisteo': 1,
  'pastor': 37,
  'david': 1,
  'gran': 219,
  'pedrada': 3,
  'valle': 13,
  'terebinto': 1,
  '<MA><1><PC><10>': 136,
  'segun': 107,
  'reyes': 22,
  '<MA><1><ND><ND><ND><ND><PC><10>': 1,
  'capitulo': 145,
  'hallaredes': 1,
  'escribe': 9,
  'tras': 47,
  'mostraros': 1,
  'hombre': 162,
  'erudito': 2,
  'humanas': 6,
  'cosmografo': 3,
  '<AC><6><PC><12>': 26,
  'haced': 4,
  'rio': 19,
  'tajo': 8,
  'vereisos': 1,
  'otra': 326,
  'famosa': 18,
  'dicho': 209,
  'espanas': 3,
  'nacimiento': 6,
  'tal': 268,
  'muere': 5,
  'mar': 33,
  'oceano': 1,
  '<MA><1><AC><4><PC><8>': 2,
  'besando': 1,
  'muros': 2,
  'ciudad': 50,
  'lisboa': 1,
  'opinion': 29,
  'arenas': 3,
  'oro': 59,
  '<ND><PC><5>': 16,
  'etc': 4,
  'ladrones': 5,
  'dire': 31,
  'caco': 4,
  'coro': 1,
  'mujeres': 33,
  'rameras': 2,
  'obispo': 1,
  'mondonedo': 1,
  '<MA><1><TI><7><PC><11>': 1,
  'prestara': 2,
  'lamia': 1,
  '<MA><1><PC><6>': 223,
  'laida': 1,
  'flora': 1,
  'cuya': 59,
  'credito': 16,
  '<AC><4><ND>': 64,
  'crueles': 3,
  'ovidio': 5,
  'entregara': 2,
  'medea': 1,
  'encantadores': 37,
  'hechiceras': 2,
  'homero': 3,
  'calipso': 1,
  'virgilio': 7,
  'circe': 1,
  'capitanes': 4,
  'valerosos': 9,
  'julio': 6,
  'cesar': 6,
  'comentarios': 1,
  '<MA><1><PC><12>': 19,
  'plutarco': 1,
  'mil': 126,
  'alejandros': 2,
  'amores': 30,
  'onzas': 1,
  'lengua': 65,
  'toscana': 2,
  'topareis': 1,
  'leon': 14,
  'hebreo': 1,
  'hincha': 1,
  'medidas': 4,
  'andaros': 1,
  'tierras': 8,
  'estranas': 5,
  '<TI><7><PC><10>': 11,
  'fonseca': 1,
  'cifra': 4,
  'acertare': 5,
  'desear': 11,
  'materia': 10,
  'resolucion': 34,
  'procureis': 2,
  'nombrar': 10,
  'nombres': 23,
  'tocar': 20,
  'historias': 38,
  'dejadme': 4,
  'cargo': 27,
  'voto': 18,
  'llenaros': 1,
  'gastar': 3,
  'cuatro': 107,
  'pliegos': 1,
  'vengamos': 4,
  'citacion': 1,
  'muy': 332,
  'facil': 15,
  '<AC><3><PC><7>': 23,
  'buscar': 64,
  'acote': 1,
  'desde': 105,
  'z': 1,
  '<AC><5><ND>': 187,
  'ese': 83,
  'abecedario': 1,
  'pondreis': 1,
  'puesto': 182,
  'clara': 30,
  'necesidad': 35,
  'teniades': 1,
  'aprovecharos': 1,
  'dellos': 63,
  'importa': 20,
  'quiza': 51,
  'habra': 31,
  'simple': 12,
  'crea': 4,
  'aprovechado': 2,
  'sencilla': 1,
  'sirva': 12,
  'servira': 2,
  'largo': 24,
  'dar': 215,
  'improviso': 14,
  'autoridad': 11,
  'ponga': 15,
  'averiguar': 8,
  'seguistes': 2,
  'yendole': 2,
  'ello': 67,
  'cuanto': 138,
  'caigo': 3,
  'ninguna': 94,
  'aquellas': 61,
  'invectiva': 1,
  'contra': 76,
  'caballerias': 45,
  '<AC><10><PC><13>': 19,
  'acordo': 9,
  'san': 18,
  'basilio': 46,
  'alcanzo': 11,
  'ciceron': 2,
  '<MA><1><AC><7><PC><9>': 10,
  'caen': 7,
  'disparates': 33,
  'puntualidades': 1,
  'observaciones': 1,
  'astrologia': 3,
  'importancia': 17,
  'geometricas': 1,
  '<AC><6><PC><13>': 8,
  'confutacion': 1,
  '<AC><11>': 149,
  'argumentos': 2,
  'sirve': 11,
  'retorica': 1,
  'predicar': 5,
  'mezclando': 2,
  'humano': 14,
  'divino': 5,
  'genero': 33,
  'mezcla': 7,
  'vestir': 6,
  'ningun': 35,
  'aprovecharse': 5,
  'imitacion': 9,
  'fuere': 43,
  'escribiendo': 4,
  'perfecta': 1,
  'tanto': 266,
  'mejor': 187,
  'escribiere': 2,
  'mira': 53,
  'deshacer': 5,
  'cabida': 2,
  'andeis': 1,
  'mendigando': 2,
  'consejos': 18,
  'fabulas': 1,
  'oraciones': 3,
  'retoricos': 1,
  'milagros': 10,
  ...},
 {'miguel': 1,
  '<MA><1>': 2,
  'de': 3,
  'cervantes': 4,
  'saavedra': 5,
  'el': 6,
  'ingenioso': 7,
  'hidalgo': 8,
  'don': 9,
  'quijote': 10,
  'la': 11,
  'mancha': 12,
  'al': 13,
  'duque': 14,
  'bejar': 15,
  '<MA><1><AC><3>': 16,
  'marques': 17,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><AC><7><MA><8>': 18,
  '<MA><1><MA><2>': 19,
  'gibraleon': 20,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><AC><9><MA><10><PC><11>': 21,
  'conde': 22,
  '<MA><1><MA><2><MA><3><MA><4><MA><5>': 23,
  'benalcazar': 24,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><AC><8><MA><9><MA><10><MA><11>': 25,
  'y': 26,
  'banares': 27,
  '<MA><1><MA><2><MA><3><TI><4><MA><5><MA><6><MA><7><MA><8><PC><9>': 28,
  'vizconde': 29,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8>': 30,
  'puebla': 31,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>': 32,
  'alcocersenor': 33,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8><MA><9><MA><10><MA><11><TI><12><MA><13><MA><14>': 34,
  'las': 35,
  '<MA><1><MA><2><MA><3>': 36,
  'villas': 37,
  'capilla': 38,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><PC><8>': 39,
  'curiel': 40,
  'burguillos': 41,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><MA><9><MA><10>': 42,
  'en': 43,
  'fe': 44,
  'del': 45,
  'buen': 46,
  'acogimiento': 47,
  'honra': 48,
  'que': 49,
  'hace': 50,
  'vuestra': 51,
  'excelencia': 52,
  'a': 53,
  'toda': 54,
  'suerte': 55,
  'libros': 56,
  '<PC><7>': 57,
  'como': 58,
  'principe': 59,
  '<AC><4>': 60,
  'tan': 61,
  'inclinado': 62,
  'favorecer': 63,
  'buenas': 64,
  'artes': 65,
  '<PC><6>': 66,
  'mayormente': 67,
  'por': 68,
  'su': 69,
  'nobleza': 70,
  'no': 71,
  'se': 72,
  'abaten': 73,
  'servicio': 74,
  'granjerias': 75,
  '<AC><9>': 76,
  'vulgo': 77,
  'he': 78,
  'determinado': 79,
  'sacar': 80,
  'luz': 81,
  'abrigo': 82,
  'clarisimo': 83,
  '<AC><6>': 84,
  'nombre': 85,
  '<MA><1><PC><11>': 86,
  'quien': 87,
  'con': 88,
  'acatamiento': 89,
  'debo': 90,
  'tanta': 91,
  'grandeza': 92,
  '<PC><9>': 93,
  'suplico': 94,
  'le': 95,
  'reciba': 96,
  'agradablemente': 97,
  'proteccion': 98,
  '<AC><10><PC><12>': 99,
  'para': 100,
  'sombra': 101,
  'aunque': 102,
  'desnudo': 103,
  'aquel': 104,
  'precioso': 105,
  'ornamento': 106,
  'elegancia': 107,
  'erudicion': 108,
  'suelen': 109,
  'andar': 110,
  'vestidas': 111,
  'obras': 112,
  'componen': 113,
  'casas': 114,
  'los': 115,
  'hombres': 116,
  'saben': 117,

In [12]:
len(quijote_corpus_tokens)

298926

In [13]:
len(quijote_corpus_diccionario_token_indices.keys())

18355

In [14]:
quijote_corpus_diccionario_token_indices["quijote"]

10

In [15]:
quijote_corpus_diccionario_token_frecuencias["quijote"]

1444

## Encontrar la distancia entre dos tokens

Sea $t_i$ el i-ésimo token, y $t_j$ el j-ésimo token, entonces, $w_{ij}$ representará la distancia entre esos dos tokens.

Para calcular $w_{ij}$ tomamos cada $t_i$ y cada t_j y anotamos la distancia inversa entre sus dos posiciones dentro del corpus, pero a mayor distancia menor relación, por lo que la suma de inversas solo aplicará a los próximos $k$ tokens y supondremos que los demás más lejanos ya afectan su contexto.

In [16]:
18355 * 18355

336906025

In [ ]:
W = {} # Matriz de correlación en forma de diccionario (matriz de diccionario x diccionario)

tokens = quijote_corpus_tokens

k = 10

for i, token_i in enumerate(tokens):
    for j in range(i + 1, min(len(tokens), i + k)):
        token_j = tokens[j]
        # print(i, token_i, j, token_j)
        d = j - i
        if not token_i in W: 
            W[token_i] = {}
        if not token_j in W[token_i]:
            W[token_i][token_j] = 0
        W[token_i][token_j] += 1 / d # PMI = ln(P(ti)/P(ti)P(tj))

    # if i > 100:
    #     break

W

{'miguel': {'<MA><1>': 5.375000000000001,
  'de': 1.5,
  'cervantes': 1.0,
  'saavedra': 0.6000000000000001,
  'el': 0.14285714285714285,
  'ingenioso': 0.1111111111111111,
  'prologo': 0.2857142857142857,
  '<MA><1><AC><4>': 0.25,
  'desocupado': 0.1111111111111111,
  'que': 0.625,
  'vendra': 0.3333333333333333,
  '<AC><7>': 0.25,
  'dice': 0.2,
  'mi': 0.16666666666666666,
  'padre': 0.14285714285714285,
  'los': 0.1111111111111111,
  'al': 0.1111111111111111},
 '<MA><1>': {'de': 734.4198412698382,
  'cervantes': 1.777777777777778,
  '<MA><1>': 392.7424603174595,
  'saavedra': 3.875,
  'el': 377.54603174602966,
  'ingenioso': 1.801190476190476,
  'hidalgo': 4.820634920634922,
  'don': 136.49801587301585,
  'quijote': 127.29960317460338,
  'la': 432.0269841269835,
  'mancha': 35.31230158730156,
  'al': 89.30515873015885,
  'duque': 19.048809523809513,
  'bejar': 0.9166666666666666,
  '<MA><1><AC><3>': 10.751190476190475,
  'marques': 1.3527777777777779,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><AC><7><MA><8>': 0.45396825396825397,
  '<MA><1><MA><2>': 1.628968253968254,
  'gibraleon': 0.125,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><AC><9><MA><10><PC><11>': 0.1111111111111111,
  'banares': 1.0,
  '<MA><1><MA><2><MA><3><TI><4><MA><5><MA><6><MA><7><MA><8><PC><9>': 0.5,
  'vizconde': 0.3333333333333333,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8>': 0.75,
  'puebla': 0.1111111111111111,
  'burguillos': 1.0,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><MA><9><MA><10>': 0.6666666666666666,
  'en': 323.1630952380949,
  'fe': 6.3468253968253965,
  'del': 178.03214285714282,
  'buen': 21.066666666666663,
  'acogimiento': 0.375,
  'y': 731.8698412698388,
  'honra': 1.2916666666666667,
  'que': 774.8646825396797,
  'hace': 4.170634920634921,
  'vuestra': 37.842460317460294,
  'excelencia': 22.34285714285714,
  'a': 407.4373015873002,
  'toda': 11.311507936507937,
  'suerte': 7.286111111111111,
  'libros': 2.1857142857142855,
  '<PC><7>': 75.11428571428588,
  'como': 93.07023809523817,
  'principe': 1.5416666666666665,
  '<AC><4>': 56.869444444444525,
  'abrigo': 0.7916666666666666,
  'clarisimo': 0.575,
  '<AC><6>': 104.95595238095244,
  'nombre': 8.058333333333335,
  '<MA><1><PC><11>': 9.26825396825397,
  'quien': 29.163095238095217,
  '<PC><6>': 108.48412698412712,
  'con': 190.579365079365,
  'acatamiento': 0.125,
  'mi': 69.09087301587311,
  'deseo': 3.625793650793651,
  'fio': 0.29166666666666663,
  '<AC><3>': 135.72658730158747,
  'no': 224.65436507936454,
  'prologo': 3.0,
  '<MA><1><AC><4>': 5.397222222222223,
  'desocupado': 0.6583333333333333,
  'lector': 1.981746031746032,
  '<ND>': 186.59404761904747,
  'sin': 30.301984126984106,
  'juramento': 0.575,
  'me': 93.29325396825402,
  'podras': 0.16666666666666666,
  'creer': 0.8666666666666666,
  'he': 15.028968253968246,
  'podido': 0.5833333333333333,
  'yo': 65.1361111111112,
  'contravenir': 0.325,
  'orden': 4.224603174603176,
  'naturaleza': 0.4444444444444444,
  'sosiego': 1.1666666666666667,
  '<PC><8>': 74.37896825396841,
  'lugar': 10.784523809523808,
  'apacible': 0.325,
  '<PC><9>': 54.782142857143,
  'amenidad': 0.125,
  'tener': 4.562301587301587,
  'un': 66.60634920634928,
  'padre': 5.48095238095238,
  'hijo': 5.6611111111111105,
  'feo': 0.16666666666666666,
  'gracia': 0.4861111111111111,
  '<PC><3>': 15.394047619047615,
  '<PC><4>': 41.01150793650793,
  'aunque': 18.35555555555555,
  'parezco': 0.16666666666666666,
  'soy': 22.101587301587298,
  'quisiera': 6.896825396825397,
  'dartela': 0.5,
  'monda': 0.25,
  'desnuda': 0.29166666666666663,
  'te': 30.946825396825382,
  'se': 315.028571428571,
  'decir': 21.154365079365068,
  'costo': 0.4206349206349206,
  'veces': 8.726984126984126,
  'tome': 1.2777777777777777,
  '<AC><5>': 198.80039682539663,
  'pluma': 0.2,
  'para': 40.90357142857143,
  'escribille': 0.14285714285714285,
  '<PC><11>': 13.850396825396816,
  '<IA><1><AC><5><PC><6>': 1.0,
  'cuando': 47.26507936507938,
  'citan': 0.25,
  'divina': 1.1666666666666667,
  'escritura': 3.375,
  '<MA><1><IC><10>': 0.6111111111111112,
  'diran': 1.2,
  'sino': 8.352380952380953,
  'son': 10.686904761904762,
  'unos': 5.769047619047619,
  'santos': 0.8289682539682539,
  'tomases': 0.125,
  'otros': 11.347222222222221,
  'doctores': 0.3333333333333333,
  'iglesia': 0.7916666666666666,
  '<MA><1><PC><8>': 42.21349206349212,
  'guardando': 0.325,
  'todo': 51.083333333333385,
  'esto': 179.76388888888886,
  'ha': 34.442857142857136,
  'carecer': 0.2,
  'libro': 8.021825396825397,
  'porque': 28.34365079365078,
  'zoilo': 0.3333333333333333,
  'o': 39.06825396825398,
  'zeuxis': 0.16666666666666666,
  '<MA><1><PC><7>': 85.32380952380964,
  'fue': 48.32777777777782,
  'fin': 22.231349206349204,
  'senor': 43.69166666666668,
  '<TI><4>': 29.53730158730156,
  'amigo': 36.971825396825395,
  'mio': 7.54920634920635,
  'prosegui': 0.1111111111111111,
  'quede': 1.5,
  'sepultado': 1.4761904761904763,
  'sus': 33.402380952380945,
  'archivos': 0.16666666666666666,
  'aqui': 22.328571428571422,
  'nace': 0.825,
  'suspension': 0.2,
  '<AC><10>': 36.44047619047619,
  'elevamiento': 0.125,
  '<PC><12>': 7.775793650793652,
  'lo': 266.4424603174603,
  'cual': 49.69920634920636,
  'dandose': 0.16666666666666666,
  'una': 40.88968253968256,
  'palmada': 0.6111111111111112,
  'agora': 7.246825396825396,
  'veo': 2.1567460317460316,
  'estais': 1.8373015873015872,
  'tan': 35.74087301587304,
  'lejos': 1.7023809523809523,
  'serlo': 0.5555555555555556,
  'falta': 2.311111111111111,
  'estadme': 1.0,
  'atento': 1.976190476190476,
  'vereis': 0.25,
  '<AC><2>': 25.649603174603154,
  'dijo': 165.32142857142858,
  '<ND><MA><2>': 32.78730158730156,
  'primero': 11.040873015873014,
  'juan': 3.416666666666667,
  'las': 109.22896825396842,
  'indias': 0.5333333333333333,
  'emperador': 1.6123015873015871,
  'trapisonda': 0.6666666666666666,
  'citar': 0.47619047619047616,
  'margenes': 0.16666666666666666,
  'los': 147.49880952380954,
  'bene': 1.0,
  'pro': 0.5,
  'toto': 0.3333333333333333,
  'libertas': 0.25,
  'venditur': 0.2,
  'auro': 0.16666666666666666,
  'luego': 27.896825396825395,
  'margen': 0.34285714285714286,
  'horacio': 0.1111111111111111,
  'trataredes': 4.111111111111111,
  'poder': 2.092857142857143,
  'muerte': 4.590873015873017,
  'acudir': 1.902777777777778,
  'mors': 1.0,
  'aequo': 0.5,
  'pulsat': 0.3333333333333333,
  'pede': 0.25,
  'pauperum': 0.2,
  'tabernas': 0.16666666666666666,
  'regumque': 0.14285714285714285,
  'turres': 0.125,
  'amistad': 2.2873015873015876,
  'amor': 5.741666666666667,
  'dios': 15.68690476190476,
  'manda': 1.2361111111111112,
  'tenga': 2.0952380952380953,
  'enemigo': 1.2595238095238095,
  'entraros': 0.125,
  'podeis': 0.3666666666666667,
  'hacer': 9.657539682539682,
  'tantico': 0.1111111111111111,
  'malos': 0.6428571428571428,
  'pensamientos': 4.336111111111111,
  '<PC><13>': 5.454761904761905,
  'acudid': 0.26785714285714285,
  'instabilidad': 0.3333333333333333,
  'amigos': 2.1484126984126983,
  'ahi': 1.4623015873015872,
  'eris': 1.1666666666666667,
  'felix': 10.291666666666666,
  'multos': 0.25,
  'numerabis': 0.2,
  'amicos': 0.16666666666666666,
  'tempora': 0.125,
  'si': 100.70198412698419,
  'fuerint': 0.5,
  'nubila': 0.3333333333333333,
  'solus': 0.2,
  'estos': 19.853571428571424,
  'latinicos': 0.3333333333333333,
  'tales': 4.431746031746032,
  'os': 15.90912698412698,
  'tendran': 0.125,
  '<AC><7>': 71.44285714285733,
  'toca': 1.1666666666666665,
  'poner': 3.5444444444444443,
  'anotaciones': 0.16666666666666666,
  'mato': 1.0,
  'gran': 12.90753968253968,
  'pedrada': 0.16666666666666666,
  '<PC><5>': 87.4293650793652,
  'mostraros': 0.25,
  'hombre': 8.510714285714286,
  'erudito': 0.29166666666666663,
  'letras': 0.9916666666666666,
  'humanas': 0.6944444444444444,
  'asi': 37.89682539682541,
  'dicho': 15.84880952380952,
  'por': 111.64444444444462,
  'rey': 3.6492063492063496,
  'ladrones': 0.41666666666666663,
  'dire': 0.3472222222222222,
  'flora': 0.5,
  '<MA><1><PC><6>': 59.5853174603175,
  'cuya': 4.731746031746032,
  'anotacion': 0.2,
  '<AC><9>': 38.138888888888886,
  'dara': 0.7361111111111112,
  'entregara': 0.5,
  'medea': 0.2,
  '<MA><1><ND>': 71.70476190476195,
  'encantadores': 0.7857142857142856,
  'tiene': 14.109126984126982,
  'calipso': 0.3333333333333333,
  'virgilio': 2.1666666666666665,
  'circe': 0.8111111111111111,
  'capitanes': 0.2777777777777778,
  'valerosos': 0.14285714285714285,
  '<PC><10>': 32.378174603174585,
  'cesar': 3.3428571428571425,
  'prestara': 0.25,
  'mismo': 7.449603174603175,
  'mil': 7.602380952380953,
  'alejandros': 0.2,
  'amores': 3.181746031746032,
  'dos': 18.44563492063491,
  'onzas': 0.125,
  'hincha': 0.3333333333333333,
  'medidas': 0.2,
  'quereis': 2.2777777777777777,
  'andaros': 0.2,
  'tierras': 0.14285714285714285,
  'estranas': 0.375,
  '<TI><7><PC><10>': 0.2777777777777778,
  '<MA><1><PC><5>': 12.05515873015873,
  'donde': 20.671428571428564,
  'cifra': 1.0873015873015872,
  'resolucion': 17.115079365079364,
  '<AC><10><PC><12>': 8.660714285714286,
  'hay': 18.42539682539682,
  'mas': 72.10396825396835,
  'vos': 7.052777777777776,
  'ahora': 15.210317460317459,
  'citacion': 0.25,
  '<AC><8>': 53.24920634920646,
  'autores': 0.125,
  'remedio': 1.3968253968253967,
  'es': 116.72658730158743,
  'muy': 15.364682539682532,
  'facil': 0.43452380952380953,
  '<AC><3><PC><7>': 0.46785714285714286,
  'hasta': 12.211507936507935,
  'z': 0.3333333333333333,
  '<MA><1><PC><2>': 1.4063492063492062,
  'decis': 0.9523809523809523,
  '<AC><5><ND>': 5.028968253968254,
  'pues': 17.131349206349196,
  'ese': 9.342460317460317,
  'abecedario': 0.3333333333333333,
  'pondreis': 0.25,
  'vuestro': 2.8301587301587303,
  '<AC><3><PC><5>': 12.604761904761904,
  'habra': 0.6777777777777777,
  'ponga': 0.1111111111111111,
  'bien': 29.081349206349202,
  'caigo': 0.2857142857142857,
  'basilio': 5.095634920634922,
  'ni': 32.61031746031746,
  'alcanzo': 1.0178571428571428,
  'ciceron': 0.30952380952380953,
  '<MA><1><AC><7><PC><9>': 0.6190476190476191,
  'caen': 0.1111111111111111,
  'aprovecharse': 0.3333333333333333,
  'imitacion': 1.3666666666666667,
  'esta': 60.52817460317466,
  'mira': 3.3761904761904757,
  '<MA><1><PC><10>': 13.56865079365079,
  'fabulas': 0.3333333333333333,
  'poetas': 0.6761904761904761,
  'oraciones': 0.7916666666666666,
  'tambien': 22.294047619047618,
  'leyendo': 0.2,
  'historia': 7.54761904761905,
  'efecto': 10.934523809523808,
  'llevad': 0.3333333333333333,
  'puesta': 1.375,
  'derribar': 0.125,
  'silencio': 4.640079365079365,
  'grande': 4.603968253968254,
  'estuve': 0.3333333333333333,
  'escuchando': 1.825,
  'opinion': 0.875,
  '<AC><7><PC><9>': 3.265079365079365,
  'quiero': 12.64960317460317,
  'encarecerte': 0.3333333333333333,
  'servicio': 0.7,
  'hago': 2.0277777777777777,
  'panza': 236.23055555555555,
  'su': 121.00436507936524,
  'escudero': 17.371031746031743,
  'salud': 2.098412698412698,
  'urganda': 0.5,
  'desconocida': 0.7777777777777778,
  'llegarte': 0.6666666666666666,
  'bue': 0.3111111111111111,
  '<ND><PC><5>': 0.6166666666666667,
  'fueres': 1.1111111111111112,
  'pan': 2.061111111111111,
  'cuepor': 0.14285714285714285,
  'ir': 2.13015873015873,
  'espiriencia': 0.3333333333333333,
  'enseque': 0.25,
  'arbol': 1.0456349206349205,
  'ma': 1.0,
  '<MA><1><ND><ND>': 6.28293650793651,
  'llega': 1.0833333333333333,
  'sombra': 0.6666666666666666,
  'noble': 0.5,
  'manchecontaras': 0.25,
  '<AC><14>': 0.5611111111111111,
  'aventu': 0.14285714285714285,
  '<ND><PC><8>': 2.0666666666666664,
  'furio': 1.0,
  '<ND><PC><7>': 1.5222222222222221,
  'templado': 0.3333333333333333,
  'enamora': 0.16666666666666666,
  '<ND><PC><9>': 1.788095238095238,
  'tobo': 0.5,
  'indiscretos': 1.1666666666666667,
  'hierogliestampes': 0.6428571428571428,
  'escu': 0.16666666666666666,
  '<ND><PC><6>': 1.9174603174603175,
  'direccion': 0.3333333333333333,
  'humi': 0.16666666666666666,
  'dira': 0.6111111111111112,
  'carta': 4.667857142857143,
  '<MA><1><ND><PC><7>': 7.416666666666666,
  'francisco': 1.125,
  'espase': 0.5,
  'queja': 1.25,
  'fortu': 0.39285714285714285,
  '<ND><ND><ND>': 0.7777777777777778,
  'cielo': 6.630158730158731,
  'le': 180.8789682539681,
  'pluque': 0.2,
  'salieses': 0.16666666666666666,
  'ladicomo': 0.125,
  'lati': 1.0,
  '<MA><1><ND><PC><6>': 0.5,
  'hablar': 2.276984126984127,
  'latines': 0.25,
  'rehu': 0.2,
  '<AC><5><ND><ND>': 0.3666666666666667,
  'despuntes': 0.5,
  'agu': 0.25,
  'alegues': 0.125,
  'metas': 0.625,
  'dibu': 0.25,
  'saber': 7.864682539682539,
  'vidas': 0.1111111111111111,
  'desati': 0.3333333333333333,
  'siendo': 5.362301587301587,
  'vidrio': 0.14285714285714285,
  'teja': 0.1111111111111111,
  'juien': 0.2,
  'obras': 1.365079365079365,
  'compose': 0.1111111111111111,
  'soneto': 10.592857142857142,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6>': 7.870238095238096,
  'tu': 26.304365079365073,
  '<MA><1><AC><3><PC><4>': 0.375,
  'imitaste': 0.16666666666666666,
  'llorosa': 0.125,
  'vida': 4.311904761904762,
  'belianis': 1.2361111111111112,
  '<MA><1><AC><8>': 3.7777777777777772,
  'grecia': 0.5833333333333333,
  'rompi': 0.47619047619047616,
  '<MA><1><AC><6><PC><7>': 0.5178571428571428,
  'corte': 0.9400793650793651,
  '<AC><6><PC><7>': 0.7361111111111112,
  'abolle': 0.14285714285714285,
  'eternice': 0.5,
  'fui': 0.5833333333333333,
  'comedido': 1.2,
  'regalado': 0.14285714285714285,
  'amante': 1.125,
  'mis': 6.997619047619049,
  'pies': 1.5694444444444446,
  'postrada': 0.25,
  'fortuna': 1.3333333333333333,
  'trajo': 0.1111111111111111,
  'senora': 14.376190476190473,
  'oriana': 0.3333333333333333,
  'dulcinea': 6.373015873015874,
  'toboso': 39.1873015873016,
  'oh': 5.320238095238096,
  'tuviera': 0.503968253968254,
  'hermosa': 4.775000000000001,
  'comodidad': 0.4583333333333333,
  'reposo': 0.26785714285714285,
  'miraflores': 1.0,
  'puesto': 11.71626984126984,
  'trocara': 1.125,
  'londres': 0.5333333333333333,
  'aldea': 2.229761904761905,
  'cuerpo': 1.3373015873015872,
  'adornara': 0.3333333333333333,
  'famoso': 2.2896825396825395,
  'caballero': 22.074603174603162,
  'alguna': 8.549206349206347,
  'desigual': 0.8095238095238094,
  'pelea': 0.6428571428571428,
  'amadis': 2.727777777777778,
  'hiciste': 0.125,
  'envidiada': 0.47619047619047616,
  'fuera': 10.39444444444444,
  'envidiara': 0.125,
  'alegre': 3.38015873015873,
  'tiempo': 10.63253968253968,
  'triste': 6.606349206349205,
  'gozara': 1.0,
  'gustos': 0.5333333333333333,
  'escote': 0.2,
  'gandalin': 0.14285714285714285,
  '<MA><1><AC><8><PC><10>': 0.125,
  'salve': 0.4583333333333333,
  'varon': 0.3666666666666667,
  'azada': 0.5,
  'hoz': 0.34285714285714286,
  'poco': 7.526984126984128,
  'repugna': 0.14285714285714285,
  'andante': 3.3662698412698417,
  'jumento': 4.121428571428572,
  'otra': 19.798412698412697,
  'vez': 11.623412698412695,
  'sancho': 117.98492063492073,
  '<MA><1><ND><PC><8>': 6.610317460317462,
  'buzcorona': 0.5,
  'reverencia': 0.7333333333333334,
  'donoso': 2.111111111111111,
  'poeta': 0.3333333333333333,
  'entreverado': 0.25,
  'rocinante': 8.904761904761905,
  'escudedel': 0.6444444444444444,
  'manchego': 0.7817460317460316,
  'quijo': 0.29166666666666663,
  'puse': 0.125,
  'razon': 2.8472222222222223,
  'estacifro': 0.2,
  'retira': 0.1111111111111111,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7><MA><8><MA><9>': 0.5,
  'famo': 0.375,
  'bisnieto': 0.16666666666666666,
  'babie': 0.1111111111111111,
  'furioso': 1.0,
  'eres': 4.688095238095238,
  'par': 1.73015873015873,
  'tampoco': 1.6444444444444444,
  'has': 8.93531746031746,
  'tenido': 2.1944444444444446,
  'perdido': 1.9301587301587302,
  'angelica': 0.1111111111111111,
  'altares': 0.3333333333333333,
  'aquel': 18.02936507936508,
  'valor': 2.019047619047619,
  'respeto': 0.14285714285714285,
  'puedo': 3.8361111111111112,
  'ser': 24.388888888888882,
  'igual': 0.375,
  'este': 41.42579365079366,
  'decoro': 0.375,
  'febo': 1.6944444444444444,
  'espada': 4.905555555555556,
  'igualo': 0.375,
  'mia': 4.052380952380952,
  'espanol': 3.361111111111111,
  '<TI><6><PC><9>': 1.25,
  'curioso': 2.166666666666667,
  'cortesano': 0.25,
  'alta': 1.3805555555555558,
  'desprecie': 1.0,
  '<AC><10><ND>': 11.670238095238092,
  'monarquia': 0.25,
  'ofrecio': 2.533333333333333,
  'rojo': 1.0,
  'vano': 0.3333333333333333,
  'deje': 1.615079365079365,
  '<AC><5><PC><6>': 5.848015873015875,
  'ver': 11.834523809523807,
  'rostro': 2.549603174603175,
  'godo': 0.4444444444444444,
  'ilustre': 0.16666666666666666,
  'claro': 1.527777777777778,
  'sois': 3.5694444444444446,
  'mundo': 3.747222222222222,
  'eterno': 0.25,
  'ella': 12.529365079365073,
  'solisdan': 1.0,
  'maguer': 0.47619047619047616,
  'vuesa': 5.626190476190477,
  'linda': 0.6428571428571428,
  'desaguisado': 1.1428571428571428,
  'contra': 3.6833333333333336,
  'comete': 0.25,
  'vuesas': 0.125,
  'cuitas': 0.2777777777777778,
  'mal': 10.578571428571427,
  'alcaguete': 0.5333333333333333,
  '<ND><PC><11>': 0.8166666666666667,
  'necio': 1.467857142857143,
  '<AC><2><PC><4>': 4.065079365079365,
  'dura': 0.125,
  'b': 1.4555555555555555,
  '<IA><1><MA><2><AC><4>': 0.8111111111111111,
  '<AC><5><PC><8>': 1.1027777777777779,
  'nunca': 4.273412698412699,
  'come': 1.3333333333333333,
  'trabaja': 0.14285714285714285,
  '<IA><1><AC><5>': 6.376984126984127,
  'cebada': 0.42063492063492064,
  'deja': 0.976190476190476,
  'amo': 10.344841269841268,
  'bocado': 0.14285714285714285,
  'cuna': 0.2,
  'mortaja': 0.125,
  'enamorado': 3.1468253968253967,
  '<IA><1><MA><2>': 1.4123015873015874,
  'necedad': 0.14285714285714285,
  'amar': 0.125,
  '<IC><5>': 1.5611111111111111,
  'prudencia': 1.0666666666666667,
  'metafisico': 0.14285714285714285,
  '<MA><1><AC><7>': 5.38452380952381,
  'quejaos': 0.14285714285714285,
  'r': 0.25,
  'bastante': 0.8611111111111112,
  'quejar': 0.1111111111111111,
  '<IC><1>': 1.0,
  'primera': 6.741666666666666,
  '<MA><1><MA><2><MA><3><MA><4><MA><5><MA><6><MA><7>': 0.8333333333333333,
  'parte': 10.746031746031742,
  '<MA><1><MA><2><MA><3><MA><4><MA><5>': 0.8428571428571429,
  'capitulo': 3.9686507936507938,
  '<MA><1><AC><5>': 8.953968253968256,
  'i': 0.125,
  'trata': 21.462301587301585,
  'condicion': 3.078968253968254,
  'ejercicio': 0.49007936507936506,
  'cuyo': 1.2805555555555557,
  'olla': 1.0,
  'algo': 5.532936507936507,
  'vaca': 0.16666666666666666,
  'carnero': 0.125,
  'resto': 1.0,
  'della': 1.5611111111111111,
  'concluian': 0.3333333333333333,
  'sayo': 0.5472222222222223,
  'velarte': 0.14285714285714285,
  'calzas': 0.1111111111111111,
  'edad': 4.429761904761905,
  'nuestro': 8.491269841269842,
  'cincuenta': 0.4916666666666667,
  'anos': 2.8884920634920634,
  'complexion': 0.5,
  'recia': 0.25,
  'seco': 0.625,
  'carnes': 0.2361111111111111,
  'importa': 1.253968253968254,
  'cuento': 3.8083333333333336,
  'basta': 0.49166666666666664,
  'silva': 0.5,
  'claridad': 0.16666666666666666,
  'prosa': 0.25396825396825395,
  'leia': 0.25,
  '<AC><4><ND>': 2.484126984126984,
  'altos': 0.26785714285714285,
  'cielos': 0.1111111111111111,
  'estas': 40.79880952380954,
  'razones': 16.837301587301585,
  'perdia': 0.8333333333333333,
  'pobre': 2.2956349206349205,
  'juicio': 1.9956349206349207,
  'estaba': 40.29325396825399,
  'heridas': 0.9166666666666666,
  'muchas': 6.50873015873016,
  'competencia': 0.3333333333333333,
  'cura': 26.55952380952381,
  '<MA><1><AC><6>': 11.314682539682536,
  'gaula': 0.8567460317460318,
  'maese': 2.9833333333333334,
  'nicolas': 0.8944444444444444,
  'alguno': 3.6996031746031752,
  'enfrasco': 0.16666666666666666,
  'tanto': 20.56944444444444,
  'ruy': 2.0,
  'diaz': 2.6666666666666665,
  'habia': 62.80555555555561,
  'sido': 5.582539682539682,

In [18]:
! /usr/local/bin/python3.12 -m pip install scipy

Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.14.1)
Requirement already satisfied: numpy<2.3,>=1.23.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scipy) (2.1.1)

[notice] A new release of pip is available: 25.0 -> 26.2.1
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [19]:
from scipy import sparse

filas = []
columnas = []
datos = []

for token_i, vecinos in W.items():
    for token_j, distancia in vecinos.items():
        i = quijote_corpus_diccionario_token_indices[token_i]
        j = quijote_corpus_diccionario_token_indices[token_j]
        filas.append(i)
        columnas.append(j)
        datos.append(distancia)

# Máxima longitud
V = max(max(filas), max(columnas)) + 1

Ws = sparse.csr_matrix(
    (datos, (filas, columnas)),
    shape=(V, V)
)

Ws.shape

(18356, 18356)

In [20]:
! /usr/local/bin/python3.12 -m pip install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (2.1.1)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.0 -> 26.2.1
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [21]:
from sklearn import decomposition

m = 8 # Número de características espaciales que se capturan de las distancias entre palabras

# Descomposición matricial por los m-autovalores principales
svd = decomposition.TruncatedSVD(m, random_state=123)

E = svd.fit_transform(Ws) # Alternativamente se puede usar PCA, pero cambia el significado

E # 18,356 x 8

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.11530770e+00,  2.44293592e+00, -1.65796671e+00, ...,
         1.09179131e+00, -2.87360573e+00, -4.41275592e-01],
       [ 1.75221437e+03,  6.99432157e+01, -1.92204540e+02, ...,
        -6.79080803e+01,  4.55132291e+01, -2.19015233e+01],
       ...,
       [ 2.18551264e-01, -7.52106495e-02, -3.11090823e-02, ...,
        -1.04660600e-01, -1.25323120e-01, -2.63489273e-02],
       [ 1.67354807e-01, -2.26518336e-02, -3.66569550e-02, ...,
        -4.90984214e-02,  2.03171900e-02,  2.78091926e-02],
       [ 2.73885884e-01, -1.58390673e-01, -1.08323722e-01, ...,
        -3.07166055e-02, -1.14767407e-02, -1.60681437e-01]])

> Correlaciones entre tokens

W - 18,356 x 18,356

i / j A B C ... XXXX
A     0 1.5 0.5 ... 0.3
B     0.8 0 ... 0
C     0   0 ... 0
...
XXXXX

In [22]:
5 * 18356

91780

In [23]:
# 5 palabras (W-18,356, W-18,356, W-18,356, W-18,356, W-18,356) - 91780 características
# 5 palabras (E-8, E-8, E-8, E-8, E-8) - 40 características

# 80 palabras (E-8, E-8, E-8, E-8, E-8, ...) - 640 características

## Entrenar un modelo con embeddings

1. Fijan las sentencias a una cantidad máxima y mínima de tokens y si hacen falta rellenan con 0 y sino truncan
2. Sentencias o textos se transforman en una matriz X de embeddings (flatten / promedio / Conv1D)
3. Predicen Y <- X

In [32]:
quijote_corpus_diccionario_token_indices["quijote"], quijote_corpus_diccionario_token_indices["hidalgo"]

(10, 8)

In [35]:
W["quijote"]["hidalgo"]

0.2361111111111111

In [37]:
E[quijote_corpus_diccionario_token_indices["quijote"]], E[quijote_corpus_diccionario_token_indices["hidalgo"]]

(array([ 474.89469185,  408.35528953, -254.3532421 , -212.63688643,
         -77.0593647 ,  177.06942154, -313.54170902,  -34.14295199]),
 array([11.2170432 ,  4.02787525, -1.26509297, -0.28355168,  1.31756483,
        -1.36825003, -1.59348598,  0.83364942]))

## Similitud coseno

$$
cos(\theta) = \frac{\overline{u} \cdot \overline{v}}{\|\overline{u}\| \|\overline{v}\|}
$$

In [41]:
import numpy

u = E[quijote_corpus_diccionario_token_indices["quijote"]]
v = E[quijote_corpus_diccionario_token_indices["hidalgo"]]

numpy.dot(u, v) / (numpy.linalg.norm(u) * numpy.linalg.norm(v))

np.float64(0.7627204764913984)

In [40]:
u = E[quijote_corpus_diccionario_token_indices["quijote"]]
v = E[quijote_corpus_diccionario_token_indices["caballero"]]

numpy.dot(u, v) / (numpy.linalg.norm(u) * numpy.linalg.norm(v))

np.float64(0.7731223623753594)

In [42]:
u = E[quijote_corpus_diccionario_token_indices["quijote"]]
v = E[quijote_corpus_diccionario_token_indices["cantar"]]

numpy.dot(u, v) / (numpy.linalg.norm(u) * numpy.linalg.norm(v))

np.float64(0.4597773047997512)

In [43]:
u = E[quijote_corpus_diccionario_token_indices["quijote"]]
v = E[quijote_corpus_diccionario_token_indices["sombra"]]

numpy.dot(u, v) / (numpy.linalg.norm(u) * numpy.linalg.norm(v))

np.float64(0.4492532113711056)

In [44]:
u = E[quijote_corpus_diccionario_token_indices["sombra"]]
v = E[quijote_corpus_diccionario_token_indices["quijote"]]

numpy.dot(u, v) / (numpy.linalg.norm(u) * numpy.linalg.norm(v))

np.float64(0.4492532113711056)

In [24]:
E

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.11530770e+00,  2.44293592e+00, -1.65796671e+00, ...,
         1.09179131e+00, -2.87360573e+00, -4.41275592e-01],
       [ 1.75221437e+03,  6.99432157e+01, -1.92204540e+02, ...,
        -6.79080803e+01,  4.55132291e+01, -2.19015233e+01],
       ...,
       [ 2.18551264e-01, -7.52106495e-02, -3.11090823e-02, ...,
        -1.04660600e-01, -1.25323120e-01, -2.63489273e-02],
       [ 1.67354807e-01, -2.26518336e-02, -3.66569550e-02, ...,
        -4.90984214e-02,  2.03171900e-02,  2.78091926e-02],
       [ 2.73885884e-01, -1.58390673e-01, -1.08323722e-01, ...,
        -3.07166055e-02, -1.14767407e-02, -1.60681437e-01]])

In [51]:
sentencia1_texto = "Me siento desdeñado por la gloriosa vida inútil"
sentencia2_texto = "Me siento desdeñado por el inútil dolor de la vida"
sentencia3_texto = "Dulcinea del Toboso es la más hermosa mujer del mundo"

sentencia1_vector = tokenizar(sentencia1_texto)
sentencia2_vector = tokenizar(sentencia2_texto)
sentencia3_vector = tokenizar(sentencia3_texto)

print(sentencia1_vector)
print(sentencia2_vector)
print(sentencia3_vector)

['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'la', 'gloriosa', 'vida', 'inutil', '<AC><4>']
['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'el', 'inutil', '<AC><4>', 'dolor', 'de', 'la', 'vida']
['dulcinea', '<MA><1>', 'del', 'toboso', '<MA><1>', 'es', 'la', 'mas', '<AC><3>', 'hermosa', 'mujer', 'del', 'mundo']

> Padding: Rellenar la sentencia a un número comprensible de tokens a procesar (30 tokens)

In [57]:
sentencia1_padding = (sentencia1_vector + ["<nulo>"] * 30)[:30]
sentencia2_padding = (sentencia2_vector + ["<nulo>"] * 30)[:30]
sentencia3_padding = (sentencia3_vector + ["<nulo>"] * 30)[:30]

print(sentencia1_padding)
print(sentencia2_padding)
print(sentencia3_padding)

['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'la', 'gloriosa', 'vida', 'inutil', '<AC><4>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']
['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'el', 'inutil', '<AC><4>', 'dolor', 'de', 'la', 'vida', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']
['dulcinea', '<MA><1>', 'del', 'toboso', '<MA><1>', 'es', 'la', 'mas', '<AC><3>', 'hermosa', 'mujer', 'del', 'mundo', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']

In [79]:
import pandas

import seaborn

def get_embedding(token):
    if not token in quijote_corpus_diccionario_token_indices:
        return numpy.zeros(m)
    return E[quijote_corpus_diccionario_token_indices[token]]

# Matriz embedding (30x8) - CNN
sentencia1_embedding = numpy.array([get_embedding(token) for token in sentencia1_padding])
sentencia2_embedding = numpy.array([get_embedding(token) for token in sentencia2_padding])
sentencia3_embedding = numpy.array([get_embedding(token) for token in sentencia3_padding])
# Matriz embedding aplanada (30*8 = 240) - NN
sentencia1_embedding_flatten = sentencia1_embedding.flatten()
sentencia2_embedding_flatten = sentencia2_embedding.flatten()
sentencia3_embedding_flatten = sentencia3_embedding.flatten()
# Matriz embedding promedio (8) - NN
sentencia1_embedding_mean = sentencia1_embedding.mean(axis=0)
sentencia2_embedding_mean = sentencia2_embedding.mean(axis=0)
sentencia3_embedding_mean = sentencia3_embedding.mean(axis=0)

# seaborn.heatmap(sentencia1_embedding, cmap="Blues")
pandas.DataFrame([
    sentencia1_embedding_mean,
    sentencia2_embedding_mean,
    sentencia3_embedding_mean,
])

,0,1,2,3,4,5,6,7
0,151.015503,3.958359,-5.284773,16.392855,2.309880,-7.659377,-5.587916,9.635637
1,291.106226,23.621508,28.880651,21.380758,6.751936,-10.495424,-10.172573,20.998027
2,258.477140,9.495925,-20.961613,42.553527,35.943287,15.925191,-7.134048,8.845339

In [83]:
quijote_narracion_dialogo = pandas.read_csv("../conjuntos/quijote_narracion_dialogo.csv")

quijote_narracion_dialogo["X_tokens"] = quijote_narracion_dialogo["X"].map(tokenizar)

quijote_narracion_dialogo

: 58 6
; 59 5
; 59 6
. 46 5
. 46 5
. 46 10
. 46 7
; 59 11
. 46 10
. 46 8
: 58 6
; 59 8
« 171 1
» 187 7
. 46 6
. 46 7
¡ 161 1
! 33 6
. 46 16
- 45 7
. 46 7
. 46 8
; 59 4
: 58 8
: 58 6
; 59 9
. 46 7
; 59 6
; 59 6
. 46 7
; 59 8
. 46 6
. 46 6
- 45 9
; 59 11
. 46 8
. 46 9
. 46 10
. 46 4
. 46 6
. 46 9
; 59 6
: 58 5
. 46 9
; 59 7
; 59 9
. 46 5
¡ 161 1
. 46 5
. 46 5
¡ 161 1
! 33 6
. 46 8
. 46 4
¡ 161 1
! 33 12
- 45 7
: 58 5
- 45 7
. 46 10
¡ 161 1
! 33 4
; 59 5
. 46 9
; 59 6
. 46 8
; 59 8
: 58 9
; 59 7
. 46 8
: 58 5
. 46 5
: 58 6
. 46 6
« 171 1
» 187 11
. 46 6
. 46 8
« 171 1
» 187 7
. 46 8
: 58 6
; 59 6
. 46 7
. 46 13
. 46 8
. 46 6
. 46 7
. 46 13
¡ 161 1
! 33 10
. 46 8
. 46 8
. 46 9
; 59 7
: 58 5
. 46 5
: 58 5
; 59 7
. 46 6
. 46 4
- 45 8
: 58 7
. 46 11
. 46 8
. 46 5
; 59 14
. 46 6
. 46 7
; 59 7
: 58 5
. 46 7
. 46 7
: 58 8
. 46 11
- 45 8
: 58 9
. 46 5
; 59 13
: 58 6
: 58 9
. 46 12
. 46 8
. 46 14
- 45 8
. 46 7
. 46 8
: 58 11
« 171 1
» 187 6
. 46 7
- 45 9
. 46 6
- 45 7
; 59 6
. 46 4
- 45 8
. 46 7
. 46 7
- 45 9
. 46 6
: 58 5
. 46 5
; 59 7
: 58 9
" 34 1
" 34 9
" 34 1
" 34 9
. 46 8
¡ 161 1
. 46 8
. 46 9
. 46 7
¡ 161 1
! 33 10
. 46 5
. 46 7
¡ 161 1
! 33 7
. 46 7
- 45 7
; 59 9
. 46 6
; 59 7
. 46 1
; 59 10
. 46 7
. 46 8
. 46 6
: 58 6
. 46 6
: 58 5
. 46 8
. 46 9
¡ 161 1
! 33 5
. 46 6
. 46 7
: 58 5
- 45 7
; 59 6
; 59 10
« 171 1
» 187 1
« 171 1
» 187 5
. 46 6
: 58 7
; 59 9
. 46 13
: 58 6
. 46 8
- 45 9
. 46 5
: 58 5
: 58 9
; 59 6
: 58 8
. 46 7
; 59 6
. 46 11
: 58 8
. 46 5
. 46 6
¡ 161 1
! 33 5
¡ 161 1
! 33 3
̈ 776 6
; 59 11
: 58 8
. 46 8
- 45 7
. 46 9
: 58 10
. 46 11
: 58 6
. 46 7
. 46 8
. 46 10
» 187 11
: 58 5
« 171 1
» 187 9
. 46 10
. 46 12
: 58 5
. 46 6
: 58 5
. 46 11
. 46 11
- 45 8
. 46 7
» 187 8
. 46 5
: 58 10
« 171 1
» 187 9
. 46 10
. 46 10
: 58 9
. 46 6
: 58 6
. 46 6
. 46 8
. 46 8
; 59 7
: 58 5
. 46 9
; 59 10
. 46 9
( 40 1
) 41 9
: 58 10
. 46 7
: 58 9
. 46 7
- 45 9
. 46 7
. 46 9
; 59 8
. 46 9
: 58 5
. 46 8
- 45 8
. 46 6
» 187 7
: 58 8
« 171 1
» 187 8
. 46 9
. 46 6
- 45 9
: 58 5
. 46 8
. 46 9
: 58 5
; 59 8
. 46 7
; 59 9
: 58 9
« 171 1
. 46 7
. 46 8
. 46 7
¡ 161 1
! 33 9
. 46 6
; 59 8
- 45 8
. 46 5
; 59 6
. 46 6
. 46 4
. 46 7
; 59 9
. 46 6
- 45 5
: 58 9
. 46 8
. 46 4
; 59 7
; 59 8
: 58 10
. 46 5
: 58 5
. 46 8
. 46 10
: 58 5
; 59 12
. 46 7
. 46 8
; 59 7
. 46 9
. 46 11
; 59 6
; 59 6
; 59 6
; 59 9
: 58 5
; 59 11
: 58 13
. 46 6
; 59 15
. 46 9
. 46 7
- 45 7
. 46 10
« 171 1
. 46 10
; 59 9
. 46 8
; 59 8
. 46 7
. 46 9
: 58 8
. 46 6
: 58 7
. 46 7
: 58 11
; 59 4
; 59 8
. 46 11
. 46 5
; 59 5
; 59 9
. 46 8
: 58 4
. 46 8
¡ 161 1
! 33 4
. 46 6
- 45 8
. 46 8
. 46 10
: 58 4
« 171 1
: 58 9
; 59 7
. 46 6
. 46 14
- 45 7
. 46 10
; 59 7
. 46 10
- 45 11
: 58 10
. 46 8
- 45 13
. 46 5
; 59 10
. 46 9
. 46 6
. 46 10
( 40 1
) 41 5
. 46 5
; 59 9
. 46 7
. 46 11
. 46 8
. 46 6
. 46 13
. 46 9
. 46 9
¡ 161 1
! 33 7
. 46 7
; 59 7
. 46 9
; 59 7
- 45 8
. 46 8
. 46 9
. 46 7
. 46 12
« 171 1
» 187 3
. 46 5
. 46 7
- 45 8
. 46 6
- 45 9
. 46 5
; 59 10
( 40 1
) 41 9
- 45 6
. 46 8
. 46 9
; 59 6
; 59 6
; 59 6
. 46 8
: 58 6
« 171 1
; 59 6
. 46 9
; 59 6
. 46 7
- 45 7
: 58 8
. 46 8
. 46 13
¡ 161 1
! 33 7
. 46 6
. 46 9
: 58 5
. 46 7
. 46 10
« 171 1
; 59 7
. 46 9
; 59 10
: 58 8
. 46 7
; 59 6
: 58 5
« 171 1
¡ 161 2
! 33 8
; 59 5
. 46 7
. 46 12
; 59 9
. 46 5
: 58 7
¡ 161 1
! 33 6
. 46 6
¡ 161 1
! 33 8
. 46 6
. 46 6
; 59 9
: 58 6
. 46 8
: 58 9
- 45 7
. 46 9
. 46 8
; 59 8
. 46 9
. 46 7
: 58 8
. 46 12
. 46 6
- 45 9
. 46 5
; 59 11
. 46 13
- 45 5
! 33 4
. 46 8
: 58 5
; 59 7
. 46 7
: 58 9
« 171 1
¡ 161 1
! 33 8
: 58 7
. 46 6
¡ 161 1
! 33 4
. 46 8
- 45 8
; 59 9
. 46 11
. 46 6
. 46 12
- 45 7
; 59 7
. 46 7
; 59 8
. 46 8
. 46 7
: 58 7
; 59 6
. 46 5
; 59 7
. 46 6
( 40 1
) 41 8
. 46 11
; 59 6
. 46 8
. 46 8
. 46 13
: 58 4
« 171 1
¡ 161 2
! 33 8
- 45 4
; 59 6
. 46 4
: 58 7
. 46 6
- 45 7
; 59 6
; 59 7
. 46 9
. 46 10
. 46 5
. 46 6
. 46 7
; 59 7
: 58 5
( 40 1
) 41 1
. 46 6
. 46 12
. 46 7
. 46 5
: 58 4
. 46 9
: 58 9
: 58 12
; 59 5
; 59 9
. 46 7
. 46 8
: 58 9
. 46 11
. 46 8
: 58 8
. 46 6
¡ 161 1
! 33 7
. 46 8
- 45 7
; 59 7
; 59 3
. 46 6
- 45 7
: 58 8
. 46 5
. 46 6
. 46 8
. 46 11
: 58 5
. 46 6
. 46 6
; 59 5
; 59 7
. 46 9
; 59 7
. 46 7
. 46 12
- 45 7
. 46 7
. 46 11
: 58 7
; 59 7
. 46 8
. 46 9
; 59 6
; 59 9
; 59 13
̈ 776 6
; 59 11
; 59 6
. 46 7
: 58 5
. 46 6
¡ 161 1
! 33 10
; 59 8
; 59 4
. 46 9
- 45 6
. 46 7
. 46 7
- 45 9
. 46 10
» 187 7
. 46 8
; 59 9
. 46 9
- 45 8
. 46 15
. 46 10
. 46 9
. 46 6
- 45 8
; 59 5
. 46 7
: 58 6
; 59 7
. 46 8
- 45 5
. 46 6
; 59 6
: 58 5
̈ 776 6
. 46 11
¡ 161 1
: 58 5
. 46 10
. 46 6
. 46 7
- 45 8
. 46 9
. 46 10
: 58 5
. 46 9
. 46 7
- 45 5
. 46 7
. 46 7
. 46 8
. 46 9
. 46 10
. 46 7
» 187 8
. 46 9
. 46 6
. 46 6
- 45 8
. 46 11
; 59 12
( 40 1
) 41 8
. 46 8
. 46 7
- 45 8
. 46 10
. 46 9
; 59 6
. 46 8
. 46 11
- 45 8
. 46 5
. 46 4
; 59 12
: 58 11
. 46 8
- 45 8
. 46 7
: 58 7
. 46 8
: 58 5
. 46 7
; 59 9
. 46 5
. 46 5
¡ 161 1
! 33 8
: 58 5
; 59 6
. 46 7
. 46 11
; 59 5
. 46 5
. 46 8
; 59 7
. 46 10
. 46 11
¡ 161 1
! 33 6
. 46 10
: 58 12
; 59 10
. 46 6
; 59 6
: 58 5
. 46 6
. 46 6
. 46 10
« 171 1
; 59 8
. 46 9
- 45 8
. 46 10
. 46 6
: 58 7
: 58 11
« 171 1
» 187 6
. 46 7
. 46 7
: 58 12
. 46 6
. 46 12
; 59 8
. 46 8
. 46 9
: 58 5
« 171 1
: 58 9
; 59 6
; 59 7
. 46 10
. 46 6
: 58 8
« 171 1
. 46 6
. 46 9
: 58 7
. 46 7
- 45 7
; 59 7
; 59 13
. 46 8
; 59 9
. 46 9
. 46 10
. 46 7
. 46 6
. 46 12
- 45 7
; 59 7
. 46 9
. 46 12
; 59 8
; 59 9
. 46 13
. 46 12
- 45 5
. 46 5
; 59 8
. 46 5
: 58 9
. 46 10
- 45 7
; 59 9
. 46 6
. 46 8
; 59 7
. 46 6
: 58 12
. 46 5
; 59 6
. 46 11
: 58 5
̈ 776 4
. 46 7
. 46 6
. 46 11
. 46 10
- 45 8
: 58 6
. 46 6
. 46 9
. 46 8
; 59 8
. 46 9
. 46 12
. 46 9
. 46 6
; 59 11
. 46 9
. 46 7
: 58 5
. 46 6
. 46 11
; 59 8
. 46 8
. 46 6
; 59 9
. 46 4
- 45 8
. 46 8
. 46 5
- 45 9
. 46 6
: 58 5
: 58 9
; 59 10
. 46 5
; 59 8
. 46 11
. 46 8
: 58 5
: 58 5
. 46 8
» 187 1
; 59 9
. 46 13
( 40 1
) 41 11
. 46 7
¡ 161 1
! 33 6
. 46 10
. 46 7
. 46 8
. 46 9
: 58 5
; 59 11
. 46 7
; 59 6
: 58 5
. 46 7
» 187 8
« 171 1
. 46 8
- 45 8
. 46 9
; 59 7
: 58 5
. 46 10
: 58 5
- 45 5
; 59 6
. 46 11
- 45 7
; 59 11
« 171 1
» 187 6
« 171 1
» 187 6
« 171 1
» 187 1
. 46 2
. 46 11
; 59 10
. 46 9
. 46 5
- 45 7
. 46 7
» 187 8
« 171 1
: 58 5
; 59 13
. 46 7
. 46 6
« 171 1
» 187 4
- 45 8
. 46 8
- 45 7
. 46 6
. 46 5
. 46 8
; 59 9
« 171 1
» 187 5
. 46 5
. 46 7
: 58 5
. 46 9
: 58 9
; 59 8
: 58 9
. 46 11
. 46 8
. 46 9
; 59 7
. 46 8
. 46 9
: 58 10
; 59 5
. 46 5
. 46 8
: 58 7
; 59 8
. 46 10
; 59 8
: 58 7
" 34 1
" 34 12
; 59 13
. 46 10
. 46 7
: 58 5
: 58 9
. 46 5
- 45 6
: 58 6
; 59 5
; 59 8
; 59 12
. 46 10
» 187 11
« 171 1
. 46 6
. 46 10
¡ 161 1
; 59 7
. 46 7
. 46 10
» 187 11
: 58 9
; 59 9
; 59 7
. 46 11
. 46 9
: 58 6
; 59 6
. 46 4
; 59 7
. 46 8
¡ 161 1
! 33 4
: 58 5
. 46 5
: 58 5
; 59 10
: 58 7
̈ 776 4
. 46 7
. 46 4
: 58 6
; 59 10
; 59 9
. 46 8
. 46 7
; 59 6
. 46 7
; 59 7
( 40 1
) 41 8
. 46 6
. 46 8
; 59 9
. 46 5
- 45 7
; 59 7
. 46 8
. 46 9
; 59 11
. 46 6
. 46 11
. 46 8
; 59 9
. 46 8
. 46 7
. 46 5
; 59 10
. 46 7
- 45 6
; 59 7
: 58 7
. 46 7
. 46 7
. 46 7
: 58 5
. 46 5
. 46 10
. 46 9
. 46 9
: 58 7
. 46 10
. 46 10
. 46 11
. 46 8
- 45 5
. 46 9
. 46 5
; 59 5
. 46 7
. 46 5
; 59 6
. 46 8
- 45 8
. 46 6
. 46 11
: 58 9
; 59 7
. 46 5
; 59 6
. 46 11
; 59 5
; 59 9
: 58 8
. 46 6
. 46 5
. 46 6
: 58 5
: 58 7
: 58 4
. 46 7
. 46 9
. 46 3
; 59 5
. 46 7
̈ 776 6
. 46 8
; 59 6
. 46 7
; 59 8
: 58 5
. 46 5
. 46 8
- 45 8
. 46 6
¡ 161 1
. 46 6
: 58 9
: 58 5
¡ 161 1
! 33 4
. 46 9
- 45 8
. 46 6
. 46 9
. 46 8
; 59 8
. 46 9
: 58 10
. 46 6
. 46 10
: 58 6
. 46 7
: 58 7
. 46 7
. 46 9
. 46 7
: 58 7
. 46 7
» 187 1
; 59 7
. 46 9
. 46 9
. 46 11
. 46 9
. 46 5
. 46 14
. 46 10
; 59 9
. 46 4
. 46 9
; 59 11
« 171 1
» 187 7
. 46 8
. 46 8
; 59 10
. 46 8
- 45 7
. 46 9
. 46 10
. 46 7
- 45 8
. 46 5
. 46 10
. 46 6
. 46 8
¡ 161 1
! 33 4
. 46 11
. 46 6
. 46 9
. 46 8
: 58 5
: 58 5
; 59 8
; 59 10
. 46 7
. 46 6
; 59 1
. 46 5
. 46 4
. 46 8
; 59 10
. 46 9
: 58 9
. 46 6
. 46 5
. 46 11
. 46 7
- 45 6
. 46 7
: 58 5
: 58 7
: 58 9
. 46 5
; 59 6
. 46 11
. 46 11
: 58 10
; 59 5
. 46 11
- 45 7
; 59 8
. 46 9
; 59 9
; 59 6
. 46 11
. 46 7
. 46 8
; 59 11
: 58 5
; 59 6
. 46 11
. 46 7
- 45 8
. 46 7
; 59 6
. 46 10
: 58 9
. 46 11
: 58 1
; 59 8
. 46 8
; 59 9
̈ 776 3
. 46 10
: 58 9
- 45 8
. 46 8
: 58 9
« 171 1
» 187 5
. 46 6
- 45 8
. 46 8
. 46 11
; 59 4
. 46 8
- 45 5
; 59 5
. 46 8
» 187 1
. 46 2
; 59 6
. 46 11
. 46 11
« 171 1
- 45 8
. 46 9
: 58 9
; 59 7
. 46 8
: 58 7
; 59 6
. 46 9
; 59 10
. 46 7
. 46 9
. 46 6
; 59 9
; 59 11
; 59 6
; 59 6
. 46 8
; 59 8
. 46 9
: 58 8
. 46 7
« 171 1
» 187 9
« 171 1
» 187 6
« 171 1
» 187 7
. 46 6
. 46 8
. 46 9
. 46 5
¡ 161 1
! 33 4
: 58 5
( 40 1
) 41 5
. 46 7
: 58 7
. 46 8
. 46 5
. 46 5
. 46 12
: 58 5
. 46 6
¡ 161 1
! 33 5
: 58 9
. 46 6
; 59 6
. 46 3
. 46 7
. 46 8
. 46 9
- 45 7
. 46 5
. 46 10
- 45 9
. 46 7
; 59 8
. 46 9
. 46 9
: 58 5
: 58 6
; 59 7
: 58 7
. 46 4
; 59 7
; 59 8
; 59 5
; 59 10
; 59 6
; 59 8
. 46 9
. 46 8
- 45 8
. 46 7
; 59 9
. 46 6
. 46 9
. 46 6
; 59 10
. 46 7
. 46 10
. 46 7
: 58 7
: 58 9
« 171 1
» 187 10
. 46 8
. 46 8
; 59 6
. 46 6
. 46 10
. 46 9
. 46 5
. 46 11
- 45 8
. 46 11
. 46 9
: 58 5
« 171 1
; 59 9
» 187 9
. 46 10
. 46 5
. 46 5
; 59 8
. 46 7
; 59 9
. 46 10
. 46 6
; 59 8
. 46 9
. 46 5
. 46 8
; 59 9
. 46 10
; 59 5
. 46 14
. 46 9
; 59 6
: 58 9
. 46 5
. 46 11
; 59 7
. 46 5
: 58 5
- 45 8
. 46 6
¡ 161 1
! 33 5
. 46 8
: 58 5
; 59 7
: 58 6
: 58 8
: 58 5
¡ 161 1
! 33 10
: 58 8
: 58 5
« 171 1
. 46 9
. 46 6
. 46 9
. 46 9
: 58 8
. 46 10
: 58 7
¡ 161 1
! 33 10
( 40 1
) 41 9
¡ 161 1
! 33 13
; 59 8
. 46 8
: 58 9
- 45 8
. 46 14
; 59 6
: 58 7
; 59 4
. 46 6
- 45 7
. 46 7
» 187 8
« 171 1
- 45 8
. 46 7
» 187 8
« 171 1
. 46 7
; 59 8
; 59 5
. 46 10
: 58 6
. 46 8
; 59 8
: 58 6
; 59 6
. 46 10
. 46 7
. 46 8
. 46 10
: 58 5
- 45 7
; 59 8
. 46 6
. 46 6
- 45 7
. 46 6
; 59 10
; 59 9
. 46 5
. 46 9
; 59 7
: 58 5
. 46 7
; 59 11
: 58 5
. 46 7
; 59 8
; 59 7
; 59 6
. 46 7
- 45 7
; 59 4
. 46 5
; 59 9
. 46 5
. 46 6
. 46 10
. 46 7
- 45 7
. 46 6
. 46 11
. 46 7
. 46 9
; 59 7
. 46 9
: 58 7
; 59 11
. 46 11
; 59 9
: 58 5
. 46 9
; 59 5
: 58 9
« 171 1
¡ 161 2
! 33 10
; 59 6
: 58 11
. 46 7
. 46 15
: 58 9
. 46 6
- 45 8
; 59 14
; 59 5
. 46 6
. 46 7
; 59 11
. 46 5
. 46 7
. 46 9
; 59 11
. 46 9
. 46 4
¡ 161 1
! 33 5
- 45 7
; 59 7
. 46 12
- 45 7
. 46 5
. 46 11
- 45 8
. 46 7
; 59 8
. 46 7
; 59 8
: 58 7
. 46 10
; 59 7
; 59 6
. 46 9
. 46 6
. 46 9
. 46 9
. 46 5
¡ 161 1
. 46 7
- 45 7
: 58 5
« 171 1
» 187 9
; 59 10
. 46 7
. 46 8
. 46 9
: 58 5
; 59 8
. 46 16
: 58 8
; 59 8
. 46 5
; 59 9
. 46 8
: 58 8
. 46 10
. 46 9
. 46 10
. 46 6
. 46 9
; 59 8
. 46 6
¡ 161 1
! 33 7
. 46 6
. 46 7
- 45 7
: 58 8
« 171 1
» 187 1
; 59 2
. 46 6
. 46 7
« 171 2
» 187 9
; 59 9
; 59 8
: 58 8
. 46 8
: 58 7
« 171 1
» 187 8
. 46 9
. 46 7
. 46 5
- 45 8
. 46 10
: 58 5
; 59 8
. 46 9
. 46 11
» 187 1
. 46 8
¡ 161 1
! 33 3
; 59 8
. 46 5
. 46 7
. 46 7
. 46 8
; 59 10
. 46 9
. 46 10
: 58 5
. 46 7
. 46 9
¡ 161 1
. 46 8
. 46 9
. 46 6
: 58 5
: 58 12
. 46 13
» 187 13
. 46 14
- 45 7
; 59 15
; 59 7
. 46 8
- 45 8
; 59 11
. 46 9
¡ 161 1
( 40 1
) 41 5
! 33 5
: 58 6
. 46 6
. 46 7
. 46 6
. 46 9
¡ 161 1
! 33 7
« 171 1
» 187 10
« 171 1
» 187 8
. 46 6
. 46 6
: 58 10
. 46 9
- 45 8
; 59 8
; 59 8
. 46 7
» 187 1
; 59 7
. 46 9
; 59 8
. 46 7
- 45 8
; 59 8
. 46 10
. 46 10
- 45 7
. 46 8
- 45 6
; 59 6
; 59 6
. 46 5
: 58 5
. 46 7
. 46 7
. 46 7
. 46 4
« 171 1
. 46 7
. 46 8
. 46 9
: 58 5
. 46 6
; 59 9
; 59 8
; 59 7
. 46 6
; 59 9
. 46 4
; 59 7
. 46 11
. 46 9
; 59 7
. 46 7
. 46 9
. 46 5
: 58 8
( 40 1
¡ 161 1
! 33 13
( 40 1
) 41 5
. 46 9
¡ 161 1
! 33 10
: 58 12
; 59 9
. 46 7
; 59 6
. 46 9
. 46 7
; 59 11
: 58 6
. 46 8
; 59 16
. 46 8
. 46 9
. 46 7
. 46 7
. 46 5
; 59 10
. 46 7
- 45 7
. 46 8
; 59 5
: 58 9
. 46 6
. 46 6
- 45 8
. 46 7
- 45 6
¡ 161 1
! 33 4
: 58 8
. 46 15
. 46 6
. 46 9
. 46 10
. 46 7
. 46 12
¡ 161 1
! 33 9
; 59 1
. 46 8
: 58 9
- 45 7
. 46 7
- 45 8
. 46 8
- 45 7
; 59 8
. 46 4
. 46 7
. 46 17
. 46 5
. 46 6
. 46 7
; 59 8
; 59 6
. 46 10
: 58 5
; 59 9
: 58 7
. 46 4
. 46 10
. 46 9
: 58 11
; 59 13
. 46 5
¡ 161 1
: 58 7
; 59 7
. 46 8
¡ 161 1
! 33 7
. 46 8
: 58 8
: 58 6
. 46 9
. 46 4
. 46 10
: 58 8
¡ 161 1
. 46 6
. 46 5
. 46 6
; 59 14
: 58 6
¡ 161 1
! 33 8
. 46 9
¡ 161 1
! 33 4
. 46 11
. 46 6
. 46 9
( 40 1
) 41 9
; 59 7
. 46 6
. 46 5
; 59 8
. 46 5
: 58 7
. 46 7
. 46 6
. 46 10
- 45 7
: 58 6
« 171 1
» 187 5
; 59 6
. 46 8
; 59 5
: 58 4
; 59 7
. 46 10
; 59 8
: 58 5
; 59 11
. 46 8
. 46 9
- 45 7
. 46 1
: 58 5
- 45 8
. 46 7
. 46 10
. 46 8
- 45 8
. 46 4
: 58 5
« 171 1
: 58 9
» 187 10
. 46 11
. 46 7
: 58 6
; 59 6
. 46 10
- 45 8
. 46 7
; 59 9
. 46 9
. 46 10
; 59 8
. 46 10
- 45 14
: 58 7
; 59 9
: 58 10
. 46 7
. 46 8
. 46 9
. 46 9
. 46 9
. 46 5
; 59 9
; 59 7
. 46 7
; 59 5
. 46 15
; 59 6
. 46 11
. 46 13
( 40 1
) 41 8
. 46 6
. 46 7
. 46 5
: 58 9
. 46 6
; 59 9
; 59 11
. 46 5
. 46 13
; 59 10
; 59 11
. 46 6
. 46 12
- 45 7
: 58 6
. 46 11
; 59 6
( 40 1
) 41 9
; 59 10
: 58 7
. 46 6
. 46 7
. 46 11
. 46 6
; 59 10
. 46 7
; 59 8
: 58 5
. 46 8
; 59 9
. 46 8
. 46 6
. 46 7
. 46 6
- 45 7
. 46 5
. 46 12
¡ 161 1
! 33 4
; 59 8
. 46 6
; 59 10
. 46 5
. 46 6
. 46 11
; 59 6
: 58 12
» 187 13
- 45 8
. 46 10
. 46 6
- 45 8
. 46 10
- 45 7
: 58 10
« 171 1
¡ 161 2
! 33 8
» 187 9
. 46 10
- 45 7
. 46 7
: 58 8
. 46 5
. 46 10
; 59 8
. 46 8
: 58 5
. 46 11
. 46 9
; 59 10
: 58 5
. 46 6
- 45 8
. 46 11
. 46 7
; 59 6
; 59 7
. 46 8
. 46 7
: 58 5
. 46 7
¡ 161 1
! 33 6
. 46 11
. 46 9
. 46 7
. 46 7
- 45 7
. 46 8
. 46 12
- 45 7
; 59 8
. 46 8
; 59 5
; 59 7
. 46 9
. 46 10
. 46 12
: 58 10
. 46 7
; 59 5
. 46 8
. 46 9
: 58 11
- 45 8
. 46 11
; 59 9
. 46 6
¡ 161 1
! 33 6
- 45 8
. 46 9
. 46 9
; 59 7
. 46 6
« 171 1
« 171 1
» 187 7
« 171 1
» 187 7
« 171 1
» 187 8
. 46 9
¡ 161 1
: 58 5
; 59 6
. 46 10
; 59 14
. 46 8
- 45 10
. 46 7
; 59 11
. 46 11
: 58 7
. 46 16
- 45 8
. 46 5
. 46 4
. 46 6
- 45 8
. 46 10
. 46 5
- 45 7
. 46 5
: 58 5
. 46 1
« 171 1
» 187 7
. 46 4
. 46 6
. 46 7
. 46 6
¡ 161 1
; 59 14
. 46 7
( 40 1
) 41 8
; 59 8
. 46 8
. 46 6
» 187 7
« 171 1
. 46 7
. 46 6
; 59 13
: 58 8
¡ 161 1
! 33 10
. 46 11
. 46 6
; 59 7
; 59 9
. 46 7
; 59 6
. 46 6
. 46 11
; 59 6
. 46 7
; 59 11
; 59 7
; 59 9
. 46 6
¡ 161 1
! 33 13
: 58 5
: 58 7
. 46 8
; 59 12
: 58 5
" 34 1
" 34 1
: 58 7
" 34 1
" 34 6
; 59 7
: 58 6
" 34 1
" 34 1
. 46 2
: 58 7
; 59 14
: 58 7
. 46 6
; 59 9
. 46 9
. 46 7
( 40 1
. 46 6
; 59 7
; 59 8
: 58 8
. 46 9
; 59 14
( 40 1
) 41 9
; 59 11
: 58 5
. 46 10
; 59 7
. 46 6
. 46 11
. 46 7
. 46 6
. 46 8
. 46 9
. 46 9
: 58 5
: 58 7
. 46 5
: 58 5
; 59 9
; 59 8
. 46 6
- 45 8
: 58 10
; 59 9
. 46 8
; 59 7
: 58 5
; 59 10
. 46 9
: 58 8
: 58 5
. 46 8
. 46 8
. 46 8
. 46 7
- 45 5
; 59 8
. 46 10
. 46 5
; 59 6
. 46 8
: 58 8
. 46 8
. 46 9
¡ 161 1
! 33 10
; 59 7
; 59 6
. 46 10
. 46 9
. 46 8
. 46 11
- 45 8
; 59 9
. 46 8
. 46 10
. 46 7
. 46 10
; 59 1
: 58 7
. 46 10
: 58 5
. 46 11
: 58 11
: 58 5
: 58 11
: 58 8
. 46 5
: 58 5
- 45 7
: 58 8
; 59 11
. 46 11
: 58 5
. 46 5
. 46 7
; 59 8
. 46 7
. 46 8
. 46 7
: 58 6
. 46 4
: 58 9
. 46 6
: 58 7
; 59 6
. 46 9
. 46 9
; 59 8
. 46 4
: 58 9
. 46 4
. 46 7
- 45 8
. 46 6
. 46 7
: 58 5
- 45 6
. 46 11
. 46 7
» 187 10
. 46 11
; 59 5
. 46 10
- 45 8
. 46 7
: 58 8
. 46 13
- 45 9
. 46 8
̈ 776 4
. 46 9
: 58 8
. 46 7
- 45 5
. 46 11
; 59 9
. 46 10
. 46 9
. 46 6
. 46 8
. 46 4
; 59 7
: 58 7
. 46 7
- 45 8
. 46 5
¡ 161 1
! 33 8
: 58 12
¡ 161 1
! 33 11
; 59 6
. 46 5
. 46 11
: 58 7
. 46 13
- 45 5
; 59 5
. 46 10
; 59 6
: 58 5
. 46 7
. 46 11
: 58 9
. 46 5
. 46 5
. 46 10
; 59 6
. 46 11
- 45 5
. 46 6
« 171 1
» 187 8
; 59 5
; 59 5
: 58 10
; 59 8
: 58 5
; 59 6
. 46 6
. 46 7
: 58 5
; 59 7
; 59 10
. 46 10
; 59 7
. 46 6
: 58 5
. 46 9
; 59 13
; 59 5
; 59 6
. 46 9
. 46 6
. 46 8
- 45 10
; 59 9
. 46 7
. 46 7
; 59 7
̈ 776 4
. 46 8
. 46 8
. 46 9
. 46 10
. 46 6
: 58 6
. 46 10
; 59 8
. 46 8
. 46 6
. 46 10
; 59 8
. 46 7
: 58 11
. 46 11
¡ 161 1
! 33 4
. 46 8
. 46 9
: 58 5
. 46 5
. 46 6
. 46 7
. 46 9
- 45 8
. 46 8
- 45 8
. 46 12
; 59 4
; 59 6
̈ 776 4
¡ 161 1
; 59 9
: 58 6
. 46 6
. 46 10
: 58 5
. 46 10
¡ 161 1
! 33 4
. 46 9
. 46 7
; 59 8
« 171 1
¡ 161 2
! 33 8
» 187 9
. 46 10
- 45 8
. 46 7
. 46 7
. 46 9
. 46 9
. 46 9
- 45 7
. 46 7
; 59 9
. 46 6
. 46 5
. 46 7
- 45 5
. 46 12
. 46 7
. 46 8
. 46 5
¡ 161 1
! 33 7
. 46 7
; 59 14
. 46 10
. 46 9
: 58 12
. 46 6
. 46 6
. 46 5
. 46 5
; 59 8
. 46 9
; 59 7
; 59 9
. 46 6
. 46 7
; 59 11
; 59 12
; 59 6
; 59 7
. 46 8
. 46 7
; 59 8
: 58 5
: 58 6
. 46 5
. 46 11
. 46 7
: 58 5
. 46 12
- 45 7
: 58 6
« 171 1
: 58 8
» 187 9
. 46 10
: 58 5
. 46 7
« 171 1
. 46 9
. 46 10
. 46 9
. 46 7
¡ 161 1
! 33 8
. 46 6
. 46 1
¡ 161 1
! 33 4
; 59 10
: 58 5
. 46 11
; 59 9
: 58 5
« 171 1
. 46 4
. 46 5
: 58 5
- 45 7
. 46 5
. 46 10
- 45 7
! 33 1
. 46 7
. 46 7
; 59 8
: 58 5
. 46 11
. 46 11
. 46 9
. 46 4
. 46 6
; 59 6
; 59 10
. 46 11
. 46 8
. 46 9
. 46 11
. 46 7
; 59 6
. 46 9
. 46 8
. 46 11
¡ 161 1
! 33 6
. 46 14
: 58 8
. 46 7
. 46 6
. 46 7
; 59 9
. 46 5
. 46 5
. 46 8
. 46 6
. 46 7
. 46 9
. 46 5
. 46 5
: 58 6
. 46 12
- 45 8
. 46 6
: 58 13
. 46 9
- 45 7
; 59 4
( 40 1
) 41 8
; 59 6
. 46 5
. 46 4
. 46 9
. 46 6
. 46 10
. 46 4
; 59 11
. 46 8
- 45 8
; 59 10
. 46 7
; 59 8
. 46 7
; 59 10
. 46 7
; 59 5
; 59 7
. 46 7
: 58 9
. 46 11
. 46 8
. 46 9
. 46 8
. 46 9
: 58 5
. 46 9
; 59 6
: 58 4
; 59 8
: 58 5
. 46 7
; 59 4
: 58 5
. 46 7
. 46 7
. 46 6
¡ 161 1
! 33 8
. 46 10
: 58 9
; 59 8
. 46 7
. 46 10
¡ 161 1
; 59 5
. 46 7
. 46 5
¡ 161 1
! 33 6
. 46 10
. 46 13
- 45 5
; 59 7
. 46 5
. 46 6
. 46 6
- 45 8
. 46 8
. 46 5
; 59 11
¡ 161 1
. 46 13
. 46 9
; 59 8
. 46 6
- 45 7
¡ 161 1
! 33 4
. 46 7
. 46 8
. 46 9
; 59 8
. 46 11
. 46 10
. 46 7
. 46 11
¡ 161 1
! 33 5
. 46 8
; 59 10
: 58 8
; 59 13
. 46 7
; 59 7
. 46 9
; 59 8
. 46 10
. 46 12
. 46 13
. 46 14
: 58 5
- 45 5
. 46 9
» 187 10
« 171 1
- 45 7
- 45 7
. 46 8
¡ 161 1
! 33 6
. 46 10
. 46 9
. 46 6
. 46 8
. 46 9
. 46 10
- 45 8
: 58 6
; 59 8
: 58 8
. 46 11
; 59 5
. 46 7
. 46 8
. 46 10
. 46 7
: 58 9
. 46 6
. 46 7
« 171 1
. 46 7
. 46 6
. 46 5
. 46 8
. 46 6
. 46 8
. 46 10
: 58 8
. 46 7
. 46 5
; 59 10
; 59 12
. 46 9
; 59 3
: 58 6
. 46 17
. 46 10
: 58 11
. 46 11
. 46 6
¡ 161 1
- 45 8
. 46 7
. 46 4
¡ 161 1
! 33 6
. 46 12
¡ 161 1
! 33 9
. 46 9
: 58 5
. 46 9
: 58 5
. 46 9
: 58 7
; 59 7
. 46 9
. 46 10
: 58 7
. 46 9
; 59 9
; 59 14
. 46 8
. 46 6
. 46 9
. 46 5
; 59 9
. 46 7
; 59 11
. 46 6
. 46 5
: 58 7
. 46 7
. 46 9
- 45 7
. 46 9
: 58 5
. 46 10
; 59 11
. 46 8
: 58 11
; 59 5
. 46 6
; 59 5
. 46 5
. 46 8
. 46 8
- 45 8
. 46 6
¡ 161 1
! 33 7
. 46 11
. 46 7
. 46 10
. 46 6
. 46 6
. 46 8
; 59 7
. 46 11
. 46 7
. 46 8
. 46 9
; 59 1
. 46 9
. 46 12
; 59 8
. 46 8
; 59 6
. 46 8
¡ 161 1
. 46 7
. 46 6
: 58 5
: 58 8
; 59 8
. 46 8
; 59 6
. 46 6
. 46 7
: 58 9
. 46 7
. 46 8
: 58 5
; 59 8
; 59 7
. 46 5
. 46 9
. 46 8
. 46 13
. 46 7
. 46 7
; 59 8
. 46 9
¡ 161 1
! 33 8
. 46 8
; 59 7
: 58 5
; 59 10
; 59 6
. 46 9
- 45 7
: 58 8
; 59 9
. 46 8
. 46 8
: 58 5
- 45 5
. 46 6
; 59 9
. 46 7
. 46 10
¡ 161 1
! 33 8
. 46 6
. 46 6
. 46 6
« 171 1
» 187 7
« 171 1
» 187 7
; 59 6
. 46 9
. 46 11
. 46 6
. 46 10
: 58 7
; 59 6
; 59 6
; 59 5
. 46 8
; 59 8
: 58 5
: 58 7
: 58 10
. 46 9
. 46 7
- 45 8
. 46 9
. 46 9
- 45 10
; 59 5
¡ 161 1
! 33 5
. 46 7
. 46 11
; 59 11
. 46 6
. 46 10
. 46 16
. 46 7
¡ 161 1
! 33 5
. 46 6
. 46 6
; 59 11
: 58 12
¡ 161 1
! 33 11
. 46 6
: 58 9
. 46 8
; 59 8
. 46 5
- 45 8
. 46 6
. 46 6
. 46 11
; 59 5
. 46 8
. 46 6
. 46 10
: 58 5
- 45 8
; 59 5
. 46 10
. 46 8
: 58 7
. 46 5
¡ 161 1
! 33 10
. 46 5
: 58 6
. 46 5
. 46 8
. 46 8
. 46 7
; 59 7
. 46 8
. 46 7
: 58 4
. 46 7
: 58 7
. 46 8
. 46 7
¡ 161 1
! 33 7
: 58 10
. 46 4
¡ 161 1
! 33 12
. 46 9
. 46 6
; 59 7
. 46 9
. 46 7
- 45 7
. 46 4
; 59 12
; 59 6
; 59 7
; 59 13
; 59 8
; 59 6
; 59 8
; 59 9
; 59 8
; 59 8
. 46 8
. 46 9
. 46 10
: 58 5
. 46 9
- 45 7
; 59 9
. 46 11
: 58 5
. 46 9
. 46 7
; 59 4
. 46 8
; 59 6
. 46 7
. 46 7
; 59 7
̈ 776 5
; 59 8
. 46 8
. 46 9
- 45 8
; 59 8
. 46 8
- 45 8
. 46 6
. 46 14
; 59 8
. 46 7
. 46 8
. 46 6
. 46 7
: 58 5
; 59 10
. 46 8
. 46 6
; 59 5
- 45 7
. 46 7
. 46 10
- 45 7
. 46 11
. 46 9
- 45 4
. 46 7
. 46 11
« 171 1
» 187 5
« 171 1
» 187 5
; 59 11
. 46 3
. 46 4
. 46 5
; 59 9
. 46 8
: 58 5
: 58 7
. 46 4
; 59 5
; 59 6
; 59 7
; 59 5
: 58 7
¡ 161 1
! 33 12
. 46 11
; 59 5
; 59 9
. 46 5
: 58 6
. 46 9
. 46 7
. 46 14
. 46 8
. 46 11
. 46 12
. 46 8
: 58 7
. 46 10
. 46 7
. 46 6
; 59 6
. 46 9
. 46 8
¡ 161 1
! 33 7
. 46 13
; 59 6
: 58 10
. 46 8
- 45 11

,X,Y1,Y2,X_tokens
0,Nadie sabe lo que está por venir: de aquí a ma...,0,0,"[nadie, <MA><1>, sabe, lo, que, esta, <AC><5>,..."
1,La de la caballería andante,0,1,"[la, <MA><1>, de, la, caballeria, <AC><10>, an..."
2,¿Ahí está el señor Florismarte?,0,1,"[ahi, <IA><1><MA><2><AC><5>, esta, <AC><5>, el..."
3,"Don Quijote mi amo, según he oído decir en est...",1,0,"[don, <MA><1>, quijote, <MA><1>, mi, amo, <PC>..."
4,¿Cómo si es así?,0,1,"[como, <IA><1><MA><2><AC><4>, si, es, asi, <AC..."
...,...,...,...,...
3702,En las suyas sintieron los que escuchado la ha...,0,0,"[en, <MA><1>, las, suyas, sintieron, los, que,..."
3703,No entiendo eso de logicuos,0,1,"[no, <MA><1>, entiendo, eso, de, logicuos]"
3704,"Quísele antecoger delante de mí y traérosle, p...",0,1,"[quisele, <MA><1><AC><4>, antecoger, delante, ..."
3705,«Nunca fuera caballero de damas tan bien servi...,0,1,"[nunca, <ND><MA><2>, fuera, caballero, de, dam..."
3706,"Besé la cruz, tomé los escudos, volvíme al ter...",1,0,"[bese, <MA><1><AC><5>, la, cruz, <PC><5>, tome..."

In [89]:
quijote_narracion_dialogo["X_tokens"].map(lambda tokens: len(tokens)).quantile(0.9)

np.float64(86.0)

In [90]:
PADDING_SIZE = 80

def padding(tokens):
    return (tokens + ["<nulo>"] * 80)[:80]

quijote_narracion_dialogo["X_sentencias"] = quijote_narracion_dialogo["X_tokens"].map(padding)

quijote_narracion_dialogo

,X,Y1,Y2,X_tokens,X_sentencias
0,Nadie sabe lo que está por venir: de aquí a ma...,0,0,"[nadie, <MA><1>, sabe, lo, que, esta, <AC><5>,...","[nadie, <MA><1>, sabe, lo, que, esta, <AC><5>,..."
1,La de la caballería andante,0,1,"[la, <MA><1>, de, la, caballeria, <AC><10>, an...","[la, <MA><1>, de, la, caballeria, <AC><10>, an..."
2,¿Ahí está el señor Florismarte?,0,1,"[ahi, <IA><1><MA><2><AC><5>, esta, <AC><5>, el...","[ahi, <IA><1><MA><2><AC><5>, esta, <AC><5>, el..."
3,"Don Quijote mi amo, según he oído decir en est...",1,0,"[don, <MA><1>, quijote, <MA><1>, mi, amo, <PC>...","[don, <MA><1>, quijote, <MA><1>, mi, amo, <PC>..."
4,¿Cómo si es así?,0,1,"[como, <IA><1><MA><2><AC><4>, si, es, asi, <AC...","[como, <IA><1><MA><2><AC><4>, si, es, asi, <AC..."
...,...,...,...,...,...
3702,En las suyas sintieron los que escuchado la ha...,0,0,"[en, <MA><1>, las, suyas, sintieron, los, que,...","[en, <MA><1>, las, suyas, sintieron, los, que,..."
3703,No entiendo eso de logicuos,0,1,"[no, <MA><1>, entiendo, eso, de, logicuos]","[no, <MA><1>, entiendo, eso, de, logicuos, <nu..."
3704,"Quísele antecoger delante de mí y traérosle, p...",0,1,"[quisele, <MA><1><AC><4>, antecoger, delante, ...","[quisele, <MA><1><AC><4>, antecoger, delante, ..."
3705,«Nunca fuera caballero de damas tan bien servi...,0,1,"[nunca, <ND><MA><2>, fuera, caballero, de, dam...","[nunca, <ND><MA><2>, fuera, caballero, de, dam..."
3706,"Besé la cruz, tomé los escudos, volvíme al ter...",1,0,"[bese, <MA><1><AC><5>, la, cruz, <PC><5>, tome...","[bese, <MA><1><AC><5>, la, cruz, <PC><5>, tome..."

In [91]:
def get_embedding_full(sentence):
    return numpy.array([get_embedding(token) for token in sentence])

def get_embedding_flatten(sentence):
    return get_embedding_full(sentence).flatten()

def get_embedding_mean(sentence):
    return get_embedding_full(sentence).mean(axis=0)

quijote_narracion_dialogo["X_mean"] = quijote_narracion_dialogo["X_sentencias"].apply(get_embedding_mean)

quijote_narracion_dialogo

,X,Y1,Y2,X_tokens,X_sentencias,X_mean
0,Nadie sabe lo que está por venir: de aquí a ma...,0,0,"[nadie, <MA><1>, sabe, lo, que, esta, <AC><5>,...","[nadie, <MA><1>, sabe, lo, que, esta, <AC><5>,...","[572.8232597845077, -0.7477138753880654, -14.1..."
1,La de la caballería andante,0,1,"[la, <MA><1>, de, la, caballeria, <AC><10>, an...","[la, <MA><1>, de, la, caballeria, <AC><10>, an...","[95.41709303355705, 10.5472752388216, 10.15833..."
2,¿Ahí está el señor Florismarte?,0,1,"[ahi, <IA><1><MA><2><AC><5>, esta, <AC><5>, el...","[ahi, <IA><1><MA><2><AC><5>, esta, <AC><5>, el...","[41.53185826514385, -0.9425919644288532, -2.56..."
3,"Don Quijote mi amo, según he oído decir en est...",1,0,"[don, <MA><1>, quijote, <MA><1>, mi, amo, <PC>...","[don, <MA><1>, quijote, <MA><1>, mi, amo, <PC>...","[317.1775653541802, -0.44958698140825104, -27...."
4,¿Cómo si es así?,0,1,"[como, <IA><1><MA><2><AC><4>, si, es, asi, <AC...","[como, <IA><1><MA><2><AC><4>, si, es, asi, <AC...","[15.64501488713285, -2.75794693518652, -0.7393..."
...,...,...,...,...,...,...
3702,En las suyas sintieron los que escuchado la ha...,0,0,"[en, <MA><1>, las, suyas, sintieron, los, que,...","[en, <MA><1>, las, suyas, sintieron, los, que,...","[368.7411147316485, 5.667445435374359, -14.067..."
3703,No entiendo eso de logicuos,0,1,"[no, <MA><1>, entiendo, eso, de, logicuos]","[no, <MA><1>, entiendo, eso, de, logicuos, <nu...","[68.00084074281433, 4.2720493331603935, 10.557..."
3704,"Quísele antecoger delante de mí y traérosle, p...",0,1,"[quisele, <MA><1><AC><4>, antecoger, delante, ...","[quisele, <MA><1><AC><4>, antecoger, delante, ...","[371.42946820376244, -10.59073207243071, -0.27..."
3705,«Nunca fuera caballero de damas tan bien servi...,0,1,"[nunca, <ND><MA><2>, fuera, caballero, de, dam...","[nunca, <ND><MA><2>, fuera, caballero, de, dam...","[170.7088670558848, 39.73073683670488, 4.52226..."
3706,"Besé la cruz, tomé los escudos, volvíme al ter...",1,0,"[bese, <MA><1><AC><5>, la, cruz, <PC><5>, tome...","[bese, <MA><1><AC><5>, la, cruz, <PC><5>, tome...","[267.4095218219415, 7.26583435487607, -18.0380..."

In [104]:
X = numpy.stack(quijote_narracion_dialogo["X_mean"].values)

X

array([[ 5.72823260e+02, -7.47713875e-01, -1.41607518e+01, ...,
         1.03482053e+01, -2.74741434e+00, -1.68462424e+00],
       [ 9.54170930e+01,  1.05472752e+01,  1.01583382e+01, ...,
        -3.75723826e+00, -3.30431198e+00,  6.60339362e+00],
       [ 4.15318583e+01, -9.42591964e-01, -2.56201584e+00, ...,
        -3.77691013e+00, -4.81048085e+00,  6.37991541e+00],
       ...,
       [ 3.71429468e+02, -1.05907321e+01, -2.75004770e-01, ...,
         8.28504555e+00, -1.28626487e+01, -1.27930371e+01],
       [ 1.70708867e+02,  3.97307368e+01,  4.52226712e+00, ...,
         1.34383357e+00,  4.62433190e+00,  7.94965909e+00],
       [ 2.67409522e+02,  7.26583435e+00, -1.80380060e+01, ...,
        -7.00683773e+00,  4.05177144e+00,  1.34721731e+01]])

In [111]:
Y1 = quijote_narracion_dialogo["Y1"]
Y2 = quijote_narracion_dialogo["Y2"]

Y = pandas.DataFrame([Y1, Y2]).T

Y

      Y1  Y2
0      0   0
1      0   1
2      0   1
3      1   0
4      0   1
...   ..  ..
3702   0   0
3703   0   1
3704   0   1
3705   0   1
3706   1   0

[3707 rows x 2 columns]

In [107]:
import keras

In [109]:
modelo = keras.Sequential([
    keras.Input(shape=(8,)),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

modelo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,410 (5.51 KB)

 Trainable params: 1,410 (5.51 KB)

 Non-trainable params: 0 (0.00 B)

In [113]:
modelo.fit(X, Y, epochs=200)

Epoch 1/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8834 - loss: 0.4178
Epoch 2/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - accuracy: 0.8697 - loss: 0.4256
Epoch 3/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - accuracy: 0.8627 - loss: 0.4411
Epoch 4/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.8757 - loss: 0.4369
Epoch 5/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.8786 - loss: 0.4301
Epoch 6/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.8793 - loss: 0.4263
Epoch 7/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.8692 - loss: 0.4331
Epoch 8/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 0.8838 - loss: 0.4274
Epoch 9/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - accuracy: 0.8822 - loss: 0.4172
Epoch 10/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.8683 - loss: 0.4399
Epoch 11/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.8831 - loss: 0.4334
Epoch 12/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step - accuracy: 0.8900 - loss: 0.4137
Epoch 13/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8857 - loss: 0.4304
Epoch 14/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - accuracy: 0.8876 - loss: 0.4140
Epoch 15/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.8896 - loss: 0.4211
Epoch 16/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - accuracy: 0.8787 - loss: 0.4142
Epoch 17/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.8886 - loss: 0.4240
Epoch 18/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.8695 - loss: 0.4171
Epoch 19/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.8966 - loss: 0.3986
Epoch 20/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.8937 - loss: 0.3999
Epoch 21/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.8873 - loss: 0.4158
Epoch 22/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.8693 - loss: 0.4384
Epoch 23/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - accuracy: 0.8978 - loss: 0.4076
Epoch 24/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8909 - loss: 0.4112
Epoch 25/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.8863 - loss: 0.4218
Epoch 26/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.8877 - loss: 0.4174
Epoch 27/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.8997 - loss: 0.3920
Epoch 28/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - accuracy: 0.8867 - loss: 0.4011
Epoch 29/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.8970 - loss: 0.3919
Epoch 30/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.8698 - loss: 0.4192
Epoch 31/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.8913 - loss: 0.3960
Epoch 32/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.8996 - loss: 0.3897
Epoch 33/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 0.8993 - loss: 0.4106
Epoch 34/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8901 - loss: 0.4040
Epoch 35/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.8926 - loss: 0.4160
Epoch 36/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - accuracy: 0.8876 - loss: 0.4369
Epoch 37/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.8743 - loss: 0.5033
Epoch 38/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - accuracy: 0.8829 - loss: 0.4320
Epoch 39/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.8946 - loss: 0.4113
Epoch 40/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.9103 - loss: 0.3762
Epoch 41/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.9064 - loss: 0.3944
Epoch 42/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - accuracy: 0.9067 - loss: 0.3866
Epoch 43/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.8799 - loss: 0.4193
Epoch 44/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.8927 - loss: 0.4004
Epoch 45/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.9001 - loss: 0.3835
Epoch 46/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - accuracy: 0.9042 - loss: 0.3735
Epoch 47/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8901 - loss: 0.4244
Epoch 48/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.9014 - loss: 0.4116
Epoch 49/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.8837 - loss: 0.4158
Epoch 50/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.8907 - loss: 0.4207
Epoch 51/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - accuracy: 0.8846 - loss: 0.4121
Epoch 52/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.9072 - loss: 0.3815
Epoch 53/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9006 - loss: 0.4067
Epoch 54/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 0.8956 - loss: 0.3858
Epoch 55/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9037 - loss: 0.4030
Epoch 56/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8919 - loss: 0.3915
Epoch 57/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 0.8864 - loss: 0.4357
Epoch 58/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.8993 - loss: 0.4012
Epoch 59/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - accuracy: 0.8973 - loss: 0.3920
Epoch 60/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.9073 - loss: 0.3818
Epoch 61/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 0.8900 - loss: 0.3892
Epoch 62/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.9036 - loss: 0.4092
Epoch 63/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.9047 - loss: 0.4156
Epoch 64/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.8927 - loss: 0.3996
Epoch 65/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.8918 - loss: 0.3963
Epoch 66/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.8998 - loss: 0.3770
Epoch 67/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.9004 - loss: 0.3859
Epoch 68/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.8927 - loss: 0.3982
Epoch 69/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.8995 - loss: 0.3880
Epoch 70/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.8684 - loss: 0.4056
Epoch 71/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step - accuracy: 0.8883 - loss: 0.3949
Epoch 72/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.9062 - loss: 0.3864
Epoch 73/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.8991 - loss: 0.4007
Epoch 74/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - accuracy: 0.8780 - loss: 0.4273
Epoch 75/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 0.8788 - loss: 0.4272
Epoch 76/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8948 - loss: 0.4080
Epoch 77/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - accuracy: 0.8898 - loss: 0.4516
Epoch 78/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9018 - loss: 0.3978
Epoch 79/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.9067 - loss: 0.3799
Epoch 80/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.9099 - loss: 0.3843
Epoch 81/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.8950 - loss: 0.4059
Epoch 82/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.9036 - loss: 0.3809
Epoch 83/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8987 - loss: 0.3918
Epoch 84/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - accuracy: 0.8985 - loss: 0.3851
Epoch 85/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.9011 - loss: 0.3792
Epoch 86/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 0.9012 - loss: 0.3711
Epoch 87/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - accuracy: 0.8976 - loss: 0.3979
Epoch 88/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - accuracy: 0.9030 - loss: 0.3693
Epoch 89/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8930 - loss: 0.3893
Epoch 90/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.8985 - loss: 0.3837
Epoch 91/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.8906 - loss: 0.3733
Epoch 92/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.9016 - loss: 0.3963
Epoch 93/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 725us/step - accuracy: 0.8997 - loss: 0.3796
Epoch 94/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.9113 - loss: 0.3815
Epoch 95/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.9042 - loss: 0.3777
Epoch 96/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.8938 - loss: 0.3755
Epoch 97/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.8990 - loss: 0.3801
Epoch 98/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.8974 - loss: 0.3952
Epoch 99/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8977 - loss: 0.3749
Epoch 100/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - accuracy: 0.8972 - loss: 0.3861
Epoch 101/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.8925 - loss: 0.3898
Epoch 102/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.8848 - loss: 0.3885
Epoch 103/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.8960 - loss: 0.3917
Epoch 104/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - accuracy: 0.8944 - loss: 0.3922
Epoch 105/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - accuracy: 0.9025 - loss: 0.3586
Epoch 106/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 0.8933 - loss: 0.3796
Epoch 107/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.9132 - loss: 0.3523
Epoch 108/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.8962 - loss: 0.3874
Epoch 109/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9045 - loss: 0.3678
Epoch 110/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.8982 - loss: 0.3971
Epoch 111/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.8995 - loss: 0.3693
Epoch 112/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.9052 - loss: 0.3770
Epoch 113/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.8977 - loss: 0.3688
Epoch 114/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.9028 - loss: 0.3660
Epoch 115/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.9045 - loss: 0.3709
Epoch 116/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 0.9089 - loss: 0.3981
Epoch 117/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9013 - loss: 0.3648
Epoch 118/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.8821 - loss: 0.3951
Epoch 119/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.8983 - loss: 0.3733
Epoch 120/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.9036 - loss: 0.3583
Epoch 121/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.9109 - loss: 0.3656
Epoch 122/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.8958 - loss: 0.3705
Epoch 123/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 0.9039 - loss: 0.3704
Epoch 124/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.8923 - loss: 0.3871
Epoch 125/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - accuracy: 0.8902 - loss: 0.3773
Epoch 126/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.8983 - loss: 0.3762
Epoch 127/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 0.9026 - loss: 0.3540
Epoch 128/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.9141 - loss: 0.3537
Epoch 129/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.8980 - loss: 0.3872
Epoch 130/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.9034 - loss: 0.3643
Epoch 131/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.9012 - loss: 0.3610
Epoch 132/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.9021 - loss: 0.3723
Epoch 133/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9019 - loss: 0.3610
Epoch 134/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.9018 - loss: 0.3866
Epoch 135/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9012 - loss: 0.3741
Epoch 136/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.9041 - loss: 0.3812
Epoch 137/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.8972 - loss: 0.3665
Epoch 138/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9057 - loss: 0.3553
Epoch 139/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - accuracy: 0.8974 - loss: 0.3627
Epoch 140/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.8878 - loss: 0.4099
Epoch 141/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9072 - loss: 0.3730
Epoch 142/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8947 - loss: 0.3648
Epoch 143/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - accuracy: 0.9008 - loss: 0.3827
Epoch 144/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 0.9026 - loss: 0.3569
Epoch 145/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - accuracy: 0.9057 - loss: 0.3558
Epoch 146/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9036 - loss: 0.3634
Epoch 147/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9025 - loss: 0.3756
Epoch 148/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step - accuracy: 0.8971 - loss: 0.3690
Epoch 149/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8963 - loss: 0.3653
Epoch 150/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.8964 - loss: 0.3717
Epoch 151/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.8996 - loss: 0.3734
Epoch 152/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - accuracy: 0.8944 - loss: 0.3775
Epoch 153/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.9142 - loss: 0.3548
Epoch 154/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.9022 - loss: 0.3597
Epoch 155/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.8913 - loss: 0.3796
Epoch 156/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9092 - loss: 0.3760
Epoch 157/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9019 - loss: 0.3545
Epoch 158/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.8937 - loss: 0.3500
Epoch 159/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.9029 - loss: 0.3501
Epoch 160/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9001 - loss: 0.3567
Epoch 161/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 0.8977 - loss: 0.3594
Epoch 162/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.8934 - loss: 0.3703
Epoch 163/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.8966 - loss: 0.3635
Epoch 164/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.9011 - loss: 0.3575
Epoch 165/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.9015 - loss: 0.3472
Epoch 166/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8997 - loss: 0.3669
Epoch 167/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.9004 - loss: 0.3856
Epoch 168/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.8906 - loss: 0.3838
Epoch 169/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.9011 - loss: 0.3460
Epoch 170/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9119 - loss: 0.3493
Epoch 171/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.9118 - loss: 0.3520
Epoch 172/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.9084 - loss: 0.3445
Epoch 173/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.8976 - loss: 0.3488
Epoch 174/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9033 - loss: 0.3555
Epoch 175/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.8982 - loss: 0.3714
Epoch 176/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.8998 - loss: 0.3467
Epoch 177/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.8969 - loss: 0.3535
Epoch 178/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.8962 - loss: 0.3818
Epoch 179/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step - accuracy: 0.8843 - loss: 0.3740
Epoch 180/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.9062 - loss: 0.3587
Epoch 181/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9049 - loss: 0.3603
Epoch 182/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8997 - loss: 0.3596
Epoch 183/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9077 - loss: 0.3474
Epoch 184/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.8946 - loss: 0.3523
Epoch 185/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.9031 - loss: 0.3490
Epoch 186/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.8932 - loss: 0.3612
Epoch 187/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9033 - loss: 0.3638
Epoch 188/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9049 - loss: 0.3594
Epoch 189/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.8878 - loss: 0.3654
Epoch 190/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.8995 - loss: 0.3519
Epoch 191/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.9050 - loss: 0.3617
Epoch 192/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step - accuracy: 0.9077 - loss: 0.3499
Epoch 193/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.8946 - loss: 0.3566
Epoch 194/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.9084 - loss: 0.3450
Epoch 195/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.9066 - loss: 0.3575
Epoch 196/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8973 - loss: 0.3682
Epoch 197/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9041 - loss: 0.3521
Epoch 198/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8932 - loss: 0.3676
Epoch 199/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - accuracy: 0.8949 - loss: 0.3547
Epoch 200/200
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.9035 - loss: 0.3502

In [117]:
sentencia1_padding = (sentencia1_vector + ["<nulo>"] * 80)[:80]
sentencia2_padding = (sentencia2_vector + ["<nulo>"] * 80)[:80]
sentencia3_padding = (sentencia3_vector + ["<nulo>"] * 80)[:80]

print(sentencia1_padding)
print(sentencia2_padding)
print(sentencia3_padding)

['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'la', 'gloriosa', 'vida', 'inutil', '<AC><4>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']
['me', '<MA><1>', 'siento', 'desdenado', '<TI><7>', 'por', 'el', 'inutil', '<AC><4>', 'dolor', 'de', 'la', 'vida', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']
['dulcinea', '<MA><1>', 'del', 'toboso', '<MA><1>', 'es', 'la', 'mas', '<AC><3>', 'hermosa', 'mujer', 'del', 'mundo', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>', '<nulo>']

In [118]:
import pandas

import seaborn

def get_embedding(token):
    if not token in quijote_corpus_diccionario_token_indices:
        return numpy.zeros(m)
    return E[quijote_corpus_diccionario_token_indices[token]]

# Matriz embedding (80x8) - CNN
sentencia1_embedding = numpy.array([get_embedding(token) for token in sentencia1_padding])
sentencia2_embedding = numpy.array([get_embedding(token) for token in sentencia2_padding])
sentencia3_embedding = numpy.array([get_embedding(token) for token in sentencia3_padding])
# Matriz embedding aplanada (80*8 = 240) - NN
sentencia1_embedding_flatten = sentencia1_embedding.flatten()
sentencia2_embedding_flatten = sentencia2_embedding.flatten()
sentencia3_embedding_flatten = sentencia3_embedding.flatten()
# Matriz embedding promedio (8) - NN
sentencia1_embedding_mean = sentencia1_embedding.mean(axis=0)
sentencia2_embedding_mean = sentencia2_embedding.mean(axis=0)
sentencia3_embedding_mean = sentencia3_embedding.mean(axis=0)

# seaborn.heatmap(sentencia1_embedding, cmap="Blues")
pandas.DataFrame([
    sentencia1_embedding_mean,
    sentencia2_embedding_mean,
    sentencia3_embedding_mean,
])

,0,1,2,3,4,5,6,7
0,56.630814,1.484385,-1.981790,6.147321,0.866205,-2.872266,-2.095468,3.613364
1,109.164835,8.858065,10.830244,8.017784,2.531976,-3.935784,-3.814715,7.874260
2,96.928927,3.560972,-7.860605,15.957573,13.478732,5.971947,-2.675268,3.317002

In [120]:
# sentencia1_texto = "Me siento desdeñado por la gloriosa vida inútil"
# sentencia2_texto = "Me siento desdeñado por el inútil dolor de la vida"
# sentencia3_texto = "Dulcinea del Toboso es la más hermosa mujer del mundo"

modelo.predict(pandas.DataFrame([
    sentencia1_embedding_mean,
    sentencia2_embedding_mean,
    sentencia3_embedding_mean,
]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step

array([[0.0172636 , 0.91705924],
       [0.03884706, 0.6633919 ],
       [0.05108311, 0.491882  ]], dtype=float32)